-- ================================================================
-- PASO 4: UPSERT items 601-900 de 1479 (actualiza o inserta)
-- ================================================================

INSERT INTO items (code, item_code, description, description_2, area_id, brand_current, supplier, category, item_type, qty_ordered)
VALUES
  ('699', '1851-4PUCK', 'Ice Pack Cal-Mil Ice Pack 1851-4PUCK', 'Cooling Puck, black (for 1851-4 jar)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Cevicheria | FOH Bar', 'UTENSILIOS', 6),
  ('643', '7186TM516', 'Bowl, 9.5" Steelite Bowl, 9.5" 7186TM516', 'Bowl, 9.5 oz, 5.0" x 1.875", Cali, Blue Lagoon, Creations, Round, Melamine, Contemporary, Casual, Convenient (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Steelite', 'Steelite', 'Cevicheria | Pool Service', 'LOZA', 12),
  ('679', '12272/02', 'Bitter / Dash Bottle Luigi Bormioli Bitter / Dash Bottle 12272/02', '10 cl - 3 ½ oz h 13.5 cm - 5 3 ⁄8” Max Ø 5.7 cm - 2 ¼”', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Luigi Bormioli', 'Proepta', 'Cevicheria | FOH Bar', 'UTENSILIOS', 6),
  ('678', '12273/02', 'Bitter / Dash Bottle Luigi Bormioli Bitter / Dash Bottle 12273/02', '10 cl - 3 ½ oz h 14.2 cm - 5 5⁄8” Max Ø 5.2 cm - 2”', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Luigi Bormioli', 'Proepta', 'Cevicheria | FOH Bar', 'UTENSILIOS', 6),
  ('680', '301-02', 'Drink Bar Mix Pourer Lid Spill-Stop Drink Bar Mix Pourer Lid 301-02', 'Dust Cap, 1/2" L, for pour spouts (285-50 & 282-50), Made in USA (one gross per poly bag, one gross per carton = 144 each, minimum order one gross)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Spill-Stop', 'Spill-Stop', 'Cevicheria | FOH Bar', 'UTENSILIOS', 2),
  ('702', 'M37023', 'Citrus Squeezer Mercer Citrus Squeezer M37023', 'Barfly Juicer, 8-7/8", with stainless steel pin, cast aluminum', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Mercer', 'Mepsa', 'Cevicheria | FOH Bar', 'UTENSILIOS', 2),
  ('635', '7178TM701', 'B&B  Steelite B&B  7178TM701', 'Plate, 6.5", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Steelite', 'Steelite', 'Cevicheria | Pool Service', 'LOZA', 12),
  ('715', 'GR-3', 'Salt Rimmer Winco Salt Rimmer GR-3', 'Glass Rimmer / Margarita Salter with 3 Compartments', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Winco', 'Mepsa', 'Cevicheria | FOH Bar', 'UTENSILIOS', 2),
  ('709', 'AS-12', 'Scoop Winco Scoop AS-12', 'Scoop, 12 oz., aluminum (hand wash only) (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Winco', 'Mepsa', 'Cevicheria | FOH Bar', 'UTENSILIOS', 6),
  ('704', 'CAP07', 'Bar Knife Cardinal Bar Knife CAP07', 'Ellis Bar Knife, 9" overall, 4-1/2" blade, stainless steel blade, POM handle, Arcoroc, Mix', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Cardinal', 'Proepta', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('713', 'CHBST112', 'Bottle Stopper American Metalcraft Bottle Stopper CHBST112', 'Champagne Bottle "Popper-Stopper", stainless steel', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('688', 'CAP09', 'Muddler Cardinal Muddler CAP09', 'Muddler, 9-5/8", stainless steel, Arcoroc, Mix', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Cardinal', 'Proepta', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('689', 'CAP01', 'Tongs, Tweezer Cardinal Tongs, Tweezer CAP01', 'Tweezers, 6-1/4", stainless steel, Arcoroc, Mix', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Cardinal', 'Proepta', 'Cevicheria | FOH Bar', 'UTENSILIOS', 8),
  ('705', 'SS-821', 'Sharpening Stone Winco Sharpening Stone SS-821', 'Sharpening Stone, 8" x 2" x 1"H, rectangular, fine/medium grain, carbonized silicone (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Winco', 'Mepsa', 'Cevicheria | FOH Bar', 'UTENSILIOS', 2),
  ('711', '7770-C', 'Bottle Stopper Franmara Bottle Stopper 7770-C', 'VacuVin® Vacuum Wine Preservation, includes: (1) 5" x 2-7/8" white pump, (1) 1-3/4" long gray stopper (carded)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Franmara', 'Franmara', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('707', '100MCCW135', 'Measuring Cup Cambro Measuring Cup 100MCCW135', 'Camwear® Measuring Cup, 1 qt., molded handle, dishwasher safe, polycarbonate, clear, NSF', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Cambro', 'Equipo Hotel', 'Cevicheria | FOH Bar', 'UTENSILIOS', 2),
  ('665', '2.5.003.00.277', 'Ice Tongs Fortessa Ice Tongs 2.5.003.00.277', 'Ice/Sugar Tong 6” (15cm)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('714', 'E5604', 'Lemon Lime Zester TableCraft Products Lemon Lime Zester E5604', 'Cash & Carry FirmGrip® Zester/Lemon Peeler, 5-3/4" x 1-1/8" x 7/8", dishwasher safe, ergonomic soft grip handle, stainless steel, black (individually carded) (1 each minimum order)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('690', 'M33071BKB', 'Vegetable Peeler, Manual Mercer Vegetable Peeler, Manual M33071BKB', 'Y-Peeler, 4" overall length, swivel blade, high-carbon steel, black handle', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Mercer', 'Mepsa', 'Cevicheria | FOH Bar', 'UTENSILIOS', 2),
  ('712', '7771-C', 'Bottle Stopper Franmara Bottle Stopper 7771-C', 'VacuVin® Vacuum Wine Stopper, 1-3/4" long, ABS plastic, gray (2 each per pack) (carded)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Franmara', 'Franmara', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('716', 'WCS871', 'Wine Key American Metalcraft Wine Key WCS871', 'Waiters Corkscrew - 4-1/2″ L x 7/8″ W x 7/8" - Stainless Steel', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', 'Cevicheria | FOH Bar', 'UTENSILIOS', 4),
  ('697', 'PF-32', 'Funnel Winco Funnel PF-32', 'Funnel, 32 oz., 6-1/4" dia., round, plastic, white (Qty Break = 6 each)', (SELECT id FROM areas WHERE name = 'Cevicheria' LIMIT 1), 'Winco', 'Mepsa', 'Cevicheria | FOH Bar', 'UTENSILIOS', 2),
  ('1938', '5593', 'Digestif Cart', 'Circa Bar Cart Elite – 5593 - W 24.25" L 34.75" H 42"', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Forbes Industries', 'Latin Hotel', NULL, 'UTENSILIOS', 1),
  ('1904', '5428.04', 'Jam Presentation', 'Glass tray - clear glass, 4 deepenings (Ø 4.6 cm), for inserts and
portion jam up to Ø 4.4 cm (e.g. Darbo portion jam, 28 g
and 40 g) - l x w x h in cm PU 23.5x6.2x3', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Zieher', 'Latin Hotel', NULL, 'UTENSILIOS', 24),
  ('1926', '20002', 'Stand for Bucket', 'CHAMPAÑERA DE ACERO INOXIDABLE MODERN', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Mepra', 'Proepta', NULL, 'UTENSILIOS', 4),
  ('1912', '82108AND0441', 'Bowl 21oz', 'William Edwards In Reed Bowl Coupe 9 1/2 In (21 Oz) Reed', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1894', '82106AND0249', 'Butter Dish / Condiment Pot', 'CONDIMENT POT D 6.5cm H 3.3cm (5.0cl) / D 2 1/2" H 1 3/8" (1 3/4oz) William Edwards Trellis', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 30),
  ('1907', '82106AND0244', 'Coupe Plate 10.5"', 'Coupe Plate, 10.5" x 0.875", Signature, Trellis, William Edwards, Round, Bone China  (minimum = case quantity) (NON STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1909', '82115AND0101V2', 'Plate 11"', 'PLATE D 30.0cm D 11 3/4" - William Edwards Diamond', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1905', '82106AND0421', 'Coupe Plate 6.5"', 'Coupe Plate, 6.5" x 0.75", Signature, Trellis, William Edwards, Round, Bone China  (minimum = case quantity) (NON STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 36),
  ('1913', '82106AND0249', 'Condiment Pot', 'Condiment Pot, 1.75 oz, 2.5" x 1.375", Signature, Trellis, William Edwards, Bone China  (minimum = case quantity) (NON STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 22),
  ('1925', '81001', 'Bucket for Stand', 'BASE PARA CHAMPAÑERA 57 CM MODERN', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Mepra', 'Proepta', NULL, 'UTENSILIOS', 4),
  ('1921', '41529-05', 'Tea Strainer', 'Paderno Tableware, Buffet, Display Tea strainer - Ø 5,0 cm - Material Stainless Steel - Look Mirror Steel', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Rosenthal Sambonet Paderno', 'Rosenthal Sambonet Paderno', NULL, 'UTENSILIOS', 12),
  ('1910', '82115AND0132', 'Pasta Bowl 11"', 'LARGE RIM BOWL - D 28.0cm H 5.7cm (60.0cl) - D 11" H 2 1/8" (21oz) William Edwards Diamond', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1906', '82106AND0163', 'Coupe Plate 8"', 'Coupe Plate, 8.25" x 0.875", Signature, Trellis, William Edwards, Round, Bone China  (minimum = case quantity) (NON STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1927', 'FL00104S6', 'Water Glass', 'Filante tumbler amber 13 oz - Set of 6', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Zafferano', 'Mepsa', NULL, 'CRISTALERIA', 44),
  ('1908', '82115AND0103', 'Plate 7"', 'PLATE D 22.0cm D 8 3/4" -William Edwards Diamond', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1911', '82108AND0332', 'Bowl 12oz', 'William Edwards In Reed Bowl Coupe 5 3/4 In (12 3/8 Oz) Reed', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1923', 'SRG3', 'Tea Stand', 'Buffet Stand, 3-tier, 12"L x 7"W x 20-1/2"H, oval, includes 6" & 7-1/4" dia. built-in white glass plates, with carry handle, steel frame, gold finish (hand wash only)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', NULL, 'UTENSILIOS', 6),
  ('1920', '82106AND0411B', 'Tea Pot', 'TEA FOR ONE TEAPOT - L 12.3cm W 10.1cm H 12.4cm (46.0cl) L 4 7/8" W 4" H 2 3/8" (16oz)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 12),
  ('1915', '82106AND0169', 'Coffee Cup Saucer', 'TEA FOR ONE SAUCER - D 14.5cm D 5 3/4"', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1916', '82108AND0145', 'Espresso Cup', 'William Edwards In Reed Espresso Cup Footed 3 5/8 In X 2 1/4 In (3 Oz) Reed', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1918', '82106AND0119', 'Sugar', 'Covered Sugar, 9.0 oz, 4.5" x 2.75", Signature, Trellis, William Edwards, Bone China  (minimum = case quantity) (NON STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 12),
  ('1914', '82106AND0411A', 'Coffee Cup', 'TEA FOR ONE CUP - L 12.7cm W 10.1cm H 6.0cm (26.0cl) - L 5" W 4" H 2 1/2" (9oz)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1917', '82108AND0146', 'Espresso Saucer', 'William Edwards In Reed Espresso Saucer 4 3/4 In Reed', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24),
  ('1939', '305 05 23 565', 'Beverage Tray', 'Round bar tray  Ø In 15', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Broggi', 'Proepta', NULL, 'UTENSILIOS', 6),
  ('1893', '01001 CANVAS', 'Napkin', 'Eco Friendly - Canvas - WHITE - 80% COTTON – 20% LINEN - 826 CANVAS
HEM: Two Hems & Two Selvedges, 4 Hems, Mitred Corners,
Product ID: 1-G1-826', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Casa Rovea', 'Casa Rovea', NULL, 'BLANCOS', 72),
  ('1919', '82106AND0120', 'Creamer', 'Milk Jug, 9.0 oz, 3.5" x 3.0" x 4.125", Signature, Trellis, William Edwards, Bone China  (minimum = case quantity) (NON STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 12),
  ('1928', 'Z7310003', 'AP Wine Glass 14oz', 'Wine Glass, 14.25 oz., 3.5"W x 9.75"H, crystalline, Stolzle, Symphony (minimum = case quantity, 24 per case) (STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 29),
  ('1941', 'V01 05 23 G11 M', 'Serving Tray', 'Gastronorm rectangular tray with handles Cm 53 x 32,5 (1/1)- In 20,7/8 x 12,3/4', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Broggi', 'Proepta', NULL, 'UTENSILIOS', 3),
  ('1929', 'Z7310000', 'Specialty Wine Glass 25oz', 'Burgundy Glass, 25 oz., 4-1/2" x 9-3/4", Symphony, Stolzle, Crystalline (minimum = case quantity, 24 per case) (Stock Item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 24),
  ('1931', 'Z1200019', 'Beer Glass', 'Beer Glass, 14 oz., 3" x 7-1/2", stemmed, Stolzle, Stemmed Beer, Soda Lime (minimum = case quantity, 24 per case) (Stock Item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 24),
  ('1902', '54.7203.6049', 'Dinner Knife', 'Table Knife, 9-3/4", monobloc, 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 29),
  ('1900', '54.7201.6040', 'Tablespoon', 'Table Spoon, 9", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 29),
  ('1901', '54.7202.6040', 'Dinner Fork', 'Table Fork, 9", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 29),
  ('1896', '54.7206.6049', 'Appetizer Knife', 'Dessert Knife, 9", monobloc, 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 29),
  ('1898', '54.7207.6040', 'Coffee / Teaspoon', 'Tea/Coffee Spoon, 5-1/2", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 44),
  ('1940', '305 12 27 503', 'Beverage Tray Non Slip Mat', 'Non-slip mat for beverage/ bar tray  Ø In  15', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Broggi', 'Proepta', NULL, 'UTENSILIOS', 6),
  ('1895', '54.7205.6040', 'Appetizer Fork', 'Dessert Fork, 8-1/4", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 29),
  ('1897', '54.7204.6040', 'Appetizer Spoon', 'Dessert Spoon, 8-1/4", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 29),
  ('1903', '54.7266.6049', 'Butter Knife / Spreader', 'Butter Knife, 6-3/4", monobloc, 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 29),
  ('1933', 'Z3460009', 'Highball', 'Water Tumbler Glass, 13-1/2 oz., 2-1/2" x 5-1/2", Kyoto, Stolzle, Crystalline (minimum = case quantity, 24 per case) (Stock Item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 24),
  ('1930', 'U1051', 'Champagne Glass', 'Chef & Sommelier  Open Up 6.75 oz. Flute Glass by Arc Cardinal', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Chef and Sommelier', 'Proepta', NULL, 'CRISTALERIA', 24),
  ('1932', 'Z3460014', 'Rock Glass', 'Whiskey Glass, 10-1/2 oz., 2-3/4" x 3 3/8", Kyoto, Stolzle, Crystalline (minimum = case quantity, 24 per case) (Stock Item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 24),
  ('1937', 'Z3460025', 'Cocktail', 'Cocktail Glass, 10.75 oz., 4.5"W x 6.75"H, crystalline, Stolzle, Kyoto (minimum = case quantity, 24 per case) (STOCK item)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 12),
  ('1924', '367.183', 'Tea Timer', 'Times Collection - Hourglass smoke/pink 5min - Dimensions H. 16 ⌀ 3,8', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Ichendorf', 'Rosenthal Sambonet Paderno', NULL, 'UTENSILIOS', 6),
  ('1936', 'P3882', 'Martini', 'Chef & Sommelier, Cabernet Cocktail 7.5 Oz (H:6.75'''' T:4.5'''' M:4.5'''' B:3.0''''), [''Krysta''], (12 PC In A Case), Minimum Purchasing Unit CS', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'CRISTALERIA', 12),
  ('1922', '903 05 81 001', 'Sugar Tongs', 'Sugar tongs -  Cm 12,6cm In 4 ,7/8"', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Broggi', 'Proepta', NULL, 'UTENSILIOS', 15),
  ('1889', '82000AND0124', 'Salt Mill', 'SALT H 6.7cm H 2 5/8" William Edwards Whiteware Collection', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'UTENSILIOS', 6),
  ('1890', '82000AND0125', 'Pepper Mill', 'PEPPER H 6.7cm H 2 5/8" William Edwards Whiteware Collection', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Steelite', 'Steelite', NULL, 'UTENSILIOS', 6),
  ('1899', '54.7209.6040', 'Demitasse Spoon', 'Demitasse Spoon, 4-1/4", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 15),
  ('1934', 'HG90079-024', 'Specialty Cocktail', 'Legend Glassware - Atlas Hi-Ball Glass, 12.5 oz., premium glass, clear (24 each per case)', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', NULL, 'CRISTALERIA', 12),
  ('1935', 'N2760', 'Gin & Tonic', 'Arcoroc, Vina Cocktail Gin 24.0 Oz (H:7.375'''' T:3.75'''' M:4.5'''' B:3.25''''), , (12 PC In A Case), Minimum Purchasing Unit CS', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'CRISTALERIA', 12),
  ('1891', 'LD090003', 'Table Lamp', 'Olimpia - GOLD - H 10.2" W bottom 3" W Top 5.9"', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'Zafferano', 'Proepta', NULL, 'UTENSILIOS', 12),
  ('1892', 'AV02', 'Bud Vase', 'Aurum - Vase/Lantern H11.75in', (SELECT id FROM areas WHERE name = 'Drawing Room' LIMIT 1), 'LSA', 'LSA', NULL, 'CRISTALERIA', 12),
  ('852', 'RL-7122-NB', 'Specialty - Molcajete Mediano', 'Molcajete Mediano 12 Cm Diametro X 6 Cm Altura Marmolina Negro/Blanco Mexicana', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Rolikka', 'Proepta', 'Beach Bar', 'UTENSILIOS', 58),
  ('846', '-', 'Specialty - Tray', 'Bandeja Pan y Manzana Alabastro Blanco 19 x 6 x 2.4 in', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Monica Calderon', 'Monica Calderon', 'Beach Bar', 'UTENSILIOS', 24),
  ('848', 'RL-7116-NB', 'Tortillero', 'Tortillero C/Tapa Marmolina 18 x 5 cm', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Rolikka', 'Proepta', 'Beach Bar', 'UTENSILIOS', 29),
  ('919', 'VM5280BK-12', 'Bar Mat', 'Versa-Mat® Bar Mat Tile/Shelf Liner, 12" x 12", interlocking, easy to cut, raised surface for airflow, dishwasher safe, rubber, black, NSF', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'San Jamar', 'Sandolat', 'Beach Bar | FOH Bar', 'UTENSILIOS', 18),
  ('827', '1-E8-527-01401', 'Napkin', 'Jackie - Color: Argento - 50% Cotton – 35% Linen – 15% Polyester
527 JACKIE - SIZE 50 x50 cm"', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'CasaRovea', 'Casa Rovea', 'Beach Bar', 'BLANCOS', 173),
  ('866', '-', 'Cooler Box  - 13 QTS', 'Yellow - Rainbow - 13 QTS - Capacity 15 cans. - 13 Qts: Ext. size 15,47″ x 10,2″ x h9,57″. Capacity 15 cans. Weight 2,20 Lb.', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Polarbox', 'Polarbox', 'Beach Bar', 'UTENSILIOS', 15),
  ('858', 'HUS0277-012', 'High Ball', 'Bold Drinkware™ - Hyde Hi-Ball Tumbler, 14 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire ( 12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 87),
  ('869', '41491G04', 'Stirrers', 'Drinks stirrers seahorse - 20,5 cm / SS Gold

Set of 4 Paderno stirrers, perfect for any Mixology-lover.', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Paderno', 'Rosenthal Sambonet Paderno', 'Beach Bar', 'UTENSILIOS', 36),
  ('870', '41491C06', 'Stirrers', 'Drinks stirrers Octopus- Stainless Steel - Look Mirror Copper - Product Size 18.5 cm', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Paderno', 'Rosenthal Sambonet Paderno', 'Beach Bar', 'UTENSILIOS', 36),
  ('847', 'rs 0035-131', 'Specialty - Bar snack', 'Botanero Gota Doble y Sencillo Fired Clay', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Monica Calderon', 'Monica Calderon', 'Beach Bar', 'UTENSILIOS', 12),
  ('842', 'rs 2202-131', 'Bowl 1', 'Stone Bowl 15.25 x 7.6cm Fired Clay', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Monica Calderon', 'Monica Calderon', 'Beach Bar', 'LOZA', 24),
  ('843', 'rs 2202-025', 'Bowl 2', 'Stone Bowl 15.25 x 7.6cm Alabastro Blanco', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Monica Calderon', 'Monica Calderon', 'Beach Bar', 'LOZA', 24),
  ('851', 'RL-7109-NB', 'Specialty - Ramekin', 'Ramekin con Pico 8x3.5 cm', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Rolikka', 'Proepta', 'Beach Bar', 'UTENSILIOS', 58),
  ('854', 'HUS088-012', 'Wine Glass', 'Bold Drinkware™ - Oasis Burgundy Glass, 11 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 58),
  ('853', 'HUS089AM-012', 'Water Glass', 'Bold Drinkware™ - Oasis Amber Tumbler Glass, 13 oz., unbreakable, polycarbonate, dishwasher safe, amber (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 58),
  ('868', 'TRPN1412RIBSVG', 'Beverage tray', '12-Sided Non-Slip Removable Insert Trays 14" Vintage Gold', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Service Ideas', 'Abastohotel', 'Beach Bar', 'UTENSILIOS', 8),
  ('860', 'HUS069-012', 'Beer Glass', 'Bold Drinkware™ - Calypso Craft Beer Glass, 13 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 44),
  ('850', 'RL-3203-NG', 'Specialty - Ramekin', 'Ramekin 2 Oz (59ml) 6x3.5cm Marmolina Negro', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Rolikka', 'Proepta', 'Beach Bar', 'UTENSILIOS', 58),
  ('865', 'HUF273-012', 'Specialty Cocktail 2', 'Bold Drinkware™ - Bora Bora Tiki, 11.25 oz., 3" dia. x 6.5"H, unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 29),
  ('845', 'PE-0032', 'Specialty - Footed Bowl m', 'Pre-Hispanic Bocha 20 cm fired clay', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Monica Calderon', 'Monica Calderon', 'Beach Bar', 'UTENSILIOS', 12),
  ('859', 'HUS0276-012', 'OF Rock Glass', 'Bold Drinkware™ - Hyde Old Fashioned Tumbler, 11 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 58),
  ('837', '7178TM708', 'Coupe Plate 11.5"', 'Coupe Plate, 11.5", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity, 6 each per case) (STOCK item)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'LOZA', 29),
  ('905', 'RA03', 'Cutting Board', 'Cutting Board, 24"W x 18"D x 2-1/4" thick, edge grain construction, Northern Hard Rock Maple, with Oil Finish, hand grips on each end, reversible', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'John Boos', 'John Boos', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('844', '-', 'Specialty - Footed Bowl s', 'Pre-Hispanic Bocha 18 cm Blueberry Marble', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Monica Calderon', 'Monica Calderon', 'Beach Bar', 'UTENSILIOS', 12),
  ('832', 'CF15105', 'Dinner Knife', 'Table Knife Matisse Vintage', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Abert', 'Proepta', 'Beach Bar', 'PLAQUE', 87),
  ('855', 'HUF107-012', 'Champagne Glass', 'Bold Drinkware™ - Oasis Stemless Champagne Glass, 6 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 29),
  ('867', 'N562603', 'Ice Bucket', 'Strahl® Design Ice Bucket, 2-1/2 qt. 9" x 6-5/8", shatter proof, hand finished, polycarbonate, clear (minimum = case quantity) (stock item) (3 per pack)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'UTENSILIOS', 15),
  ('838', '7178TM706', 'Bowl 9.5"', 'Bowl, 1.5 qt, 9.5" x 2.0", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity, 6 each per case) (STOCK item)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'LOZA', 36),
  ('857', 'HUS057-012', 'Hurricane', 'Bold Drinkware™ - Calypso Hurricane Glass, 11 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 29),
  ('849', 'RL-7110-MD', 'Cuchara madera', 'Cuchara Chica
P/Salsa
3 x 9 cm', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Rolikka', 'Proepta', 'Beach Bar', 'PLAQUE', 72),
  ('864', 'HUS8037-012', 'Specialty Cocktail 1', 'Bold Drinkware™ - Bimini Stack Hi-Ball Glass, 12.75 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 29),
  ('830', 'CF15101', 'Dinner Spoon', 'Table Spoon Matisse Vintage', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Abert', 'Proepta', 'Beach Bar', 'PLAQUE', 87),
  ('831', 'CF15102', 'Dinner Fork', 'Table fork Matisse Vintage', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Abert', 'Proepta', 'Beach Bar', 'PLAQUE', 87),
  ('862', 'HUS380-012', 'Cocktail', 'Bold Drinkware™ - Maldives Wine / Cocktail, 13oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 29),
  ('861', 'HU1022-012', 'Coupe', 'Bold Drinkware™ - Charisma Coupe, 7 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 29),
  ('836', '7178TM702', 'Plate 9"', 'Plate, 9.0", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'LOZA', 36),
  ('839', '7178TM704', 'Bowl 7"', 'Bowl, 30.25 oz, 7.0" x 2.625", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'LOZA', 36),
  ('856', 'HU5024-012', 'Martini', 'Bold Drinkware™ - Maldives Martini, 8.75oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 29),
  ('863', 'HUS360-012', 'Shot Glass', 'Bold Drinkware™ - Hyde Shot, 2 oz., unbreakable, polycarbonate, dishwasher safe, crystal sapphire (12 each per case)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', 'Beach Bar', 'CRISTALERIA', 48),
  ('833', 'CF15121', 'Coffee / Tea Spoon', 'Tea spoon Matisse Vintage', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Abert', 'Proepta', 'Beach Bar', 'PLAQUE', 87),
  ('875', '23183-21', 'Condiment Caddy', 'Sydney 3 Jar Display-Oak', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('840', '7178TM705', 'Bowl 5"', 'Bowl, 4.25 oz, 5.375" x 2.0", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity, 6 each per case) (STOCK item)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'LOZA', 36),
  ('902', 'JP9730', 'Juicer, Lever / Crank Type', 'Cash & Carry Big Squeeze™ Juice Press, 11-1/2" x 7" x 17", manual, accommodates 5-3/4" glass, 3-pinion design, hand wash only, 18/8 stainless steel cone, cast iron construction, black coated finish, NSF (1 each minimum order)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('903', 'BP003733', 'Bottle Opener', 'GIO, Sealife Bottle Openers, Antique Brass, Set of 3 - Bottle Openers: 4"L x 2"W x 1"H, 5"L x 3"W x 1"H, 6"L x 2.5"W x 1"H', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Blue Pheasant', 'Blue Pheasant', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('835', '7178TM701', 'B&B', 'Plate, 6.5", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'LOZA', 36),
  ('873', 'M37219ANG', 'Mixing Glass', 'Barfly® Diamond Lattice Mixing Tin, 21 oz. (625 ml.), double-wall insulated, pouring spout, dishwasher safe, 18/8 stainless steel, Antique Gold plated satin finish', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('828', 'RL-7101-P-NB', 'Pepper Mill', 'Pimentero
Marmolina
5 x 3 cm', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Rolikka', 'Proepta', 'Beach Bar', 'UTENSILIOS', 12),
  ('829', 'RL-7101-S-NB', 'Salt Mill', 'Salero
Marmolina
5 x 3 cm', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Rolikka', 'Proepta', 'Beach Bar', 'UTENSILIOS', 12),
  ('917', 'SI6000', 'Ice Tote', 'Saf-T-Ice® Tote, 6 gallon, polycarbonate, rubber handle, with tri-grip feature, includes Saf-T-Ice® HACCP hanger for elevation to waist level, NSF', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'San Jamar', 'Sandolat', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('896', 'M37012ANG', 'Bar Spoon', 'Barfly® Classic Bar Spoon, 11-13/16" (30 cm), weighted teardrop shaped end, twisted stem, one-piece, 18/8 stainless steel core, Antique Gold-plated finish', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 4),
  ('909', '1851-5', 'Storage Jar / Ingredient Canister, Glass', 'Mixology Jar, 32 oz. capacity, 5-1/4" dia., x 4-1/2"H, double walled insulated base, stainless steel solid lid with silicone lining, glass, clear (cold pucks sold separately)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('900', '285-50', 'Liquor Pourer', 'Spill-Stop® Tapered Pourer, seamless spout, with poly-kork, controlled medium speed, chrome, Made in USA (packed one dozen per poly bag, one gross per carton = 144 each, minimum order 1 gross)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Spill-Stop', 'Spill-Stop', 'Beach Bar | FOH Bar', 'UTENSILIOS', 48),
  ('841', '7178TM703', 'Bowl 4.75"', 'Bowl, 5.25 oz, 4.75" x 1.0", Salinas, Grigio, Creations, Round, Melamine,  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Steelite', 'Steelite', 'Beach Bar', 'LOZA', 29),
  ('901', 'PE-AMS-03', 'Mandoline', 'MANDOLINA AJUSTABLE REBANADA JULIANA DE PLASTICO', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Matfer', 'Proepta', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('907', '1851-4', 'Storage Jar / Ingredient Canister, Glass', 'Mixology Jar, 16 oz. capacity, 4-1/4" dia. x 4"H, double walled insulated base, stainless steel solid lid with silicone lining, glass, clear (cold pucks sold separately)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('890', 'M37005ANG', 'Jigger', 'Barfly® Japanese Style Jigger, 1 & 2 oz., with internal marking lines, 18/8 stainless steel core, Antique Gold-plated finish', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('912', 'BM-1812K', 'Bar Mat', 'Service Mat, 18" x 12", rubber, black, NSF (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Winco', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('876', '3309-60', 'Napkin Holder', 'Bamboo bar napkin Holder  I 5” x 5"', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('877', '3308-60', 'Straw Holder', 'Aspen Stir Stick Organizer I 5.25” W x 5.25” D x 5.5” H', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('891', 'M37008ANG', 'Cocktail Shaker 28 oz', 'Barfly® Shaker, 28 oz., 3-5/8" dia. x 7"H, capped bottom, 18/8 stainless steel core, satin finish interior, Antique Gold-plated finish exterior', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('893', 'M37026ANG', 'Bar Strainer', 'Barfly® Spring Bar Strainer, 6" overall length, heavy duty, 2-prong, replaceable spring, hanging hole, 18/8 stainless steel core, Antique Gold-plated finish', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('834', 'CF15122', 'Demitasse Spoon', 'Moka / Demitasse spoon Matisse Vintage', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Abert', 'Proepta', 'Beach Bar', 'PLAQUE', 29),
  ('894', 'M37028ANG', 'Julep Strainer', 'Barfly® Julep Strainer, 6-1/2" overall length, welded handle with hanging hole, 18/8 stainless steel core, Antique Gold-plated exterior', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('892', 'M37007ANG', 'Cocktail Shaker 18 oz', 'Barfly® Shaker, 18 oz., 3-1/2" dia. x 5"H, capped bottom, 18/8 stainless steel core, satin finish interior, Antique Gold-plated finish exterior', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('910', '1851-5PUCK', 'Ice Pack', 'Cooling Puck, black (for 1851-5 jar)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('871', '1220 WOOD', 'Fruit Stand Small', 'Mendocino Small Footed Bowl - 5"Dx4"H', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Impulse', 'Impulse', 'Beach Bar', 'UTENSILIOS', 1),
  ('872', '1222 WOOD', 'Fruit Stand Large', 'Mendocino Large Footed Bowl - 11"Dx5.25"H', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Impulse', 'Impulse', 'Beach Bar', 'UTENSILIOS', 1),
  ('904', 'M15500', 'Channel Knife', 'Mercer Cutlery Channel Knife, stain-resistant steel, molded slip-resistant polypropylene handle', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('895', 'M37025', 'Mesh Strainer', 'Barfly® Mesh Strainer, 3-1/2" dia. bowl, 10-3/8" overall length, fine-mesh, front rest loop, rod handle, 18/8 stainless steel', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('915', '160-02', 'Bar Mat', 'Bar Mat, 24"L x 3-1/4"W x 1/2"H, non-slip, rubber, black', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Spill-Stop', 'Spill-Stop', 'Beach Bar | FOH Bar', 'UTENSILIOS', 4),
  ('908', '1851-4PUCK', 'Ice Pack', 'Cooling Puck, black (for 1851-4 jar)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('887', '12273/02', 'Bitter / Dash Bottle', '10 cl - 3 ½ oz h 14.2 cm - 5 5⁄8” Max Ø 5.2 cm - 2”', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Luigi Bormioli', 'Proepta', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('888', '12272/02', 'Bitter / Dash Bottle', '10 cl - 3 ½ oz h 13.5 cm - 5 3 ⁄8” Max Ø 5.7 cm - 2 ¼”', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Luigi Bormioli', 'Proepta', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('889', '301-02', 'Drink Bar Mix Pourer Lid', 'Dust Cap, 1/2" L, for pour spouts (285-50 & 282-50), Made in USA (one gross per poly bag, one gross per carton = 144 each, minimum order one gross)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Spill-Stop', 'Spill-Stop', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('911', 'M37023', 'Citrus Squeezer', 'Barfly Juicer, 8-7/8", with stainless steel pin, cast aluminum', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('924', 'GR-3', 'Salt Rimmer', 'Glass Rimmer / Margarita Salter with 3 Compartments', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Winco', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('918', 'AS-12', 'Scoop', 'Scoop, 12 oz., aluminum (hand wash only) (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Winco', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 3),
  ('913', 'CAP07', 'Bar Knife', 'Ellis Bar Knife, 9" overall, 4-1/2" blade, stainless steel blade, POM handle, Arcoroc, Mix', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cardinal', 'Proepta', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('922', 'CHBST112', 'Bottle Stopper', 'Champagne Bottle "Popper-Stopper", stainless steel', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('897', 'CAP09', 'Muddler', 'Muddler, 9-5/8", stainless steel, Arcoroc, Mix', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cardinal', 'Proepta', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('898', 'CAP01', 'Tongs, Tweezer', 'Tweezers, 6-1/4", stainless steel, Arcoroc, Mix', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cardinal', 'Proepta', 'Beach Bar | FOH Bar', 'UTENSILIOS', 4),
  ('914', 'SS-821', 'Sharpening Stone', 'Sharpening Stone, 8" x 2" x 1"H, rectangular, fine/medium grain, carbonized silicone (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Winco', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('920', '7770-C', 'Bottle Stopper', 'VacuVin® Vacuum Wine Preservation, includes: (1) 5" x 2-7/8" white pump, (1) 1-3/4" long gray stopper (carded)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Franmara', 'Franmara', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('916', '100MCCW135', 'Measuring Cup', 'Camwear® Measuring Cup, 1 qt., molded handle, dishwasher safe, polycarbonate, clear, NSF', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Cambro', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('874', '2.5.003.00.277', 'Ice Tongs', 'Ice/Sugar Tong 6” (15cm)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('923', 'E5604', 'Lemon Lime Zester', 'Cash & Carry FirmGrip® Zester/Lemon Peeler, 5-3/4" x 1-1/8" x 7/8", dishwasher safe, ergonomic soft grip handle, stainless steel, black (individually carded) (1 each minimum order)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('899', 'M33071BKB', 'Vegetable Peeler, Manual', 'Y-Peeler, 4" overall length, swivel blade, high-carbon steel, black handle', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Mercer', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('921', '7771-C', 'Bottle Stopper', 'VacuVin® Vacuum Wine Stopper, 1-3/4" long, ABS plastic, gray (2 each per pack) (carded)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Franmara', 'Franmara', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('925', 'WCS871', 'Wine Key', 'Waiters Corkscrew - 4-1/2″ L x 7/8″ W x 7/8" - Stainless Steel', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', 'Beach Bar | FOH Bar', 'UTENSILIOS', 2),
  ('906', 'PF-32', 'Funnel', 'Funnel, 32 oz., 6-1/4" dia., round, plastic, white (Qty Break = 6 each)', (SELECT id FROM areas WHERE name = 'Beach Bar' LIMIT 1), 'Winco', 'Mepsa', 'Beach Bar | FOH Bar', 'UTENSILIOS', 1),
  ('769', 'UHRS-10', 'Hot and Cold transport trolley', 'Heated & Refrigerated Cabinet, mobile, (10) 18" x 26" or (20) 12" x 20" pan capacity, 4-1/2" OC, adjustable to 1-1/2" increments, Dual-temp electronic controls, top mounted forced air heating system, adjustable thermostat, ­90°F to 190°F (heated) & 33°F to 38°F (refrigerated) temperature range, bottom mounted compressor, insulated, (1) flush mounted door, wrap around bumper, stainless steel construction, polyurethane casters (2) rigid & (2) swivel with brakes, 1/4 HP, UL, cUL, UL EPH Classified, DOE 17 - 110 VOLTS', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'FWE', 'Abastohotel', 'In Room Dining', 'UTENSILIOS', 2),
  ('769.1', 'ASHM-1000-BQ2-96', NULL, 'CARRO BANQUETERO 96 PLATOS 1 PUERTA 120V', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), NULL, 'Abastohotel', NULL, NULL, 2),
  ('762', 'RST-01', 'Room Table Trollys', 'Room Service Table / Trolley - 5 Fold Room Service Trolley - Accommodates two Food Warmers - Wilsonart timbergrain laminated top - Black PVC edging - Pewter powdercoated frame - Heavy duty wheels (2 lockable) - A. Fully-folded:
12” W x 36” D x 36” H
305 W x 915 D x 915 H (mm)
B. Wings-down:
27” W x 36” D x 30¾” H
685 W x 915 D x 782 (mm)
C. Deployed:
41¾” W x 36” D x 30¾” H
1062 W x 915 D x 782 (mm)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Ramler', 'Proepta', 'In Room Dining', 'UTENSILIOS', 18),
  ('760', 'SET_LT_WN002', 'Tray and Stand', 'Walnut Folding Tray Table / Folding Tray Table (Tall - Locking): L:600 × W:400 × H:749 mm (L:23.6 ×W: 15.7 × H:29.5 in)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Craster', 'Proepta', 'In Room Dining', 'UTENSILIOS', 30),
  ('763', 'IHB-01', 'Hotboxes', 'Food Warmer / Hot Box - Black stainless steel - Double walled for insulation - Removable shelves - Digital thermostat controller - Power Consumption: 120/240V, 300W - Power Surge Protection - Preset Temperature: 165°F / 73°C - (Not including handles): 161/8” W x 15½” D x 18” H 410 W x 395 D x 460 H (mm)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Ramler', 'Proepta', 'In Room Dining', 'UTENSILIOS', 18),
  ('764', 'PRT-01', 'Storage Racks', 'Powered Food Warmer Rack with storage space for six trolleys - Black powdercoated steel frame - 6 socket power outlet - Power Surge Protection - 4 Heavy duty wheels with brake - Deploys 6 Hot Boxes and 6 trolleys
DIMENSIONS
83 7/8” W x 22” D x 75 3/4” H
2130 W x 560 D x 1925 H (mm)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Ramler', 'Proepta', 'In Room Dining', 'UTENSILIOS', 3),
  ('768', 'TBD', 'Overlay', 'TBD depending on final ID', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Casa Rovea', 'Casa Rovea', 'In Room Dining | Linen', 'BLANCOS', 60),
  ('767', 'TBD', 'Underlay', 'TBD depending on final ID', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Casa Rovea', 'Casa Rovea', 'In Room Dining | Linen', 'BLANCOS', 30),
  ('721', '5428.04', 'Jam Presentation', 'tray 4-hole - clear glass - 23.5x6.2x3cm - 6pcs (6 per case). clear glass, 4 deepenings (Ø 4.6 cm), for inserts and portion jam up to Ø 4.4 cm (e.g. Darbo portion jam, 28 g
and 40 g)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'ZIEHER', 'Latin Hotel', 'In Room Dining', 'UTENSILIOS', 24),
  ('752', '7401MM120', 'Soup Thermos .7 L White', 'Server Vacuum Insulated Stainless Liner w/ Wood Handle White (0.7 L)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Steelite', 'Steelite', 'In Room Dining', 'UTENSILIOS', 36),
  ('766', 'TBD', 'Damper', 'Damper for Ramler room service table troley', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Casa Rovea', 'Casa Rovea', 'In Room Dining | Linen', 'BLANCOS', 24),
  ('753', '7401MM121', 'Thermos 1 L White', 'Server Vacuum Insulated Stainless Liner w/ Wood Handle White (1 L)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Steelite', 'Steelite', 'In Room Dining', 'UTENSILIOS', 24),
  ('754', '7401MM123', 'Thermos 1 L Champagne', 'Server Vacuum Insulated Stainless Liner w/ Wood Handle Champagne (1 L)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Steelite', 'Steelite', 'In Room Dining', 'UTENSILIOS', 24),
  ('720', '411272', 'Butter Presentation', '(112726) Butter Dish, (SHIPS FROM FRANCE), 3-1/2" dia. x 3/4"H (base dimensions only), round, with glass dome, stackable, shockproof, thermal shock resistant (-148°F to + 176°F), food safe, non-porous, dishwasher safe, Nacryl® resin, white, Mealplak (10 year warranty against UV, when used with translucent side up, contact factory for details) Made in France (US stocked item)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Revol', 'Proepta', 'In Room Dining', 'UTENSILIOS', 24),
  ('751', 'RK-UBCBVCL16P3', 'Plate Covers', 'CAMPANA P/PLATO HONDO GOURMET 16 CM BRAVURA *ACABADO ESPECIAL
SILVER*', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'RAK', 'Proepta', 'In Room Dining', 'UTENSILIOS', 36),
  ('717', '39899', 'Salt Mill', 'Line Salt Mill, 5"H (12 cm), beech wood and aluminum, natural', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Peugeot', 'Peugeot', 'In Room Dining', 'UTENSILIOS', 24),
  ('718', '39929', 'Pepper Mill', 'Line Pepper Mill, 5"H (12 cm), beech wood and aluminum, carbon', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Peugeot', 'Peugeot', 'In Room Dining', 'UTENSILIOS', 24),
  ('728', '1170500001', 'Dinner Spoon', 'Dinner Spoon Gualtiero Marchesi St. steel 8 1/2"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 72),
  ('729', '1170500002', 'Dinner Fork', 'Dinner Fork Gualtiero Marchesi St. steel 8 1/2"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 72),
  ('730', '1170500005', 'Dinner Knife', 'Dinner Knife Gualtiero Marchesi St. steel 9 1/2"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 72),
  ('723', '1170500012', 'Appetizer Fork', 'Dessert Fork Gualtiero Marchesi St. steel 7 7/8"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 72),
  ('724', '1170500015', 'Appetizer Knife', 'Dessert Knife Gualtiero Marchesi St. steel 8 3/8"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 72),
  ('725', '1170500011', 'Appetizer Spoon', 'Dessert Spoon Gualtiero Marchesi St. steel 7 7/8"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 72),
  ('726', '1170500021', 'Coffee/Tea Spoon', 'Tea Spoon Gualtiero Marchesi St. steel 5 1/2"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 119),
  ('735', 'BCFRFP29', 'Flat Plate 11"', 'Fedra Round flat plates with rim Ø 29 cm / Ø 11 1/2” 12', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 29),
  ('731', 'BCSPCP15', 'B&B 6"', 'Spectra Coupe Plate, 5.9", bone china (24 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 72),
  ('737', 'BCBVGD29', 'Gourmet Deep Plate 11"', 'Bravura Ø 29 cm - 31 cl. Ø 11 1/2” - 10 1/2 oz. 6', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 22),
  ('744', 'BCFRSC28', 'Stackable Coffee Cup', 'Fedra Stackable Coffee Cup, Ht. 6 cm - 29 cl Ht. 2 2/5” - 9 4/5 oz 12', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 51),
  ('733', 'BCSPDC23', 'Coupe Deep Plate, 9"', 'Spectra Coupe Deep Plate, 9.05", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 29),
  ('734', 'BCFRCP27', 'Coupe Plate 10.5"', 'Fedra Coupe Plate, 10.63", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 29),
  ('756', '26.112412', 'AP Wine Glass 13oz', 'Zwiesel Glass Pure Sauvignon Blanc Glass, (0) 13.8 oz., dishwasher safe, lead free, sheer rim, crystal glass (0.34 each weight) (Per case = 6 each) (ecomm dealers 4 case increments; special box will be added cost)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Fortessa', 'Hotel Depot', 'In Room Dining', 'CRISTALERIA', 47),
  ('732', 'BCSPCP21', 'Coupe Plate, 8"', 'Spectra Coupe Plate, 8.25", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 29),
  ('749', 'BCFRCR15', 'Creamer', 'Fedra Ceamer Ht. 8.5 cm - 21 cl Ht. 3 1/3” - 7 oz', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 36),
  ('745', 'BCFRSA17', 'Coffee Saucer', 'Fedra Saucer, Ø 17.5 cm / Ø 6 4/5”, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 51),
  ('755', '12635/01', 'Water Glass', 'Double Old Fashioned Glass, 12.25 oz., pure and transparent, durable, break resistant, heat treated, machine-blown SPARKX® lead-free crystal glass, Top Class by Luigi Bormioli (Core collection)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Luigi Bormioli', 'Proepta', 'In Room Dining', 'CRISTALERIA', 72),
  ('757', '26.112415', 'Champagne Glass', 'Zwiesel Glass Pure Champagne Flute Glass, (7) 7.1 oz., dishwasher safe, lead free, sheer rim, crystal glass (0.3 each weight) (Per case = 6 each) (ecomm dealers 4 case increments; special box will be added cost)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Fortessa', 'Hotel Depot', 'In Room Dining', 'CRISTALERIA', 42),
  ('750', 'BCFRSH01', 'Sugar Holder', 'Fedra Sugar Pack Holder, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 36),
  ('742', 'BCFRCS37M', 'Soup Cup without Handle', 'Fedra Cream Soup Bowl, 12.5 oz., with no handles, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 22),
  ('738', 'BCBVCB50', 'Cereal Bowl', 'Bravura Low Cereal Bowl Ø 15 cm - 50 cl Ø 6” - 16 5/6 oz 12', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 29),
  ('765', 'TBD', 'Off White Napkins', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'GT Linens', 'YEKALON', 'In Room Dining | Linen', 'BLANCOS', 144),
  ('719', 'TV4', 'Bread Bag', 'Canvas Bag, 7-1/2" dia. x 5"H, round, 3-layer, cream inside/gray outside', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', 'In Room Dining', 'UTENSILIOS', 24),
  ('741', 'BCBVJG35', 'Sauce Pourer', 'Bravura Jug
Ht. 16.5 cm - 36 cl
Ht. 6 1/2” - 12 2/7 oz 6', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 15),
  ('739', 'BCBVFBW10', 'Bowl 4"', 'Bravura Bowl, Ø 10 cm - 20 cl. Ø 4” - 6 3/4 oz (12 per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 29),
  ('736', 'BCBVCL16', 'Cover for Gourmet Deep Plates', 'Bravura Ø 16.5 cm - Ht. 9 cm. Ø 6 1/2” - Ht. 3 1/2”. 4', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 22),
  ('759', '3460012-6', 'High Ball Glass', 'Kyoto Longdrink 15 ½ oz - Set of six. - 463ml | 15 ½ oz
H 165 mm | 6 ½"
Ø 62 mm | 2 ½"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Stolzle', 'Proepta', 'In Room Dining', 'CRISTALERIA', 42),
  ('758', '3460015-6', 'OF Rock Glass', 'Kyoto Old Fashioned Tumbler 14 ½ oz - Set of six. - 433 ml | 14 ½ oz
H 94 mm | 3 ¾"
Ø 80 mm | 3"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Stolzle', 'Proepta', 'In Room Dining', 'CRISTALERIA', 42),
  ('743', 'BCFRSA18', 'Soup Cup Saucer', 'Fedra Saucer, 7.08", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 22),
  ('740', 'BCFRBW50', 'Bowl 17oz - Ø 5 1/5”', 'Fedra Bowl, 16.9 oz., bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 15),
  ('748', 'BCFRBR01', 'Ramekin', 'Fedra Butter Ramekin, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 26),
  ('746', 'BCFRSC09', 'Stackable Expresso Cup', 'Fedra Expresso Cup, Ht. 2 1/6” - 3 3/8 oz., bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 15),
  ('727', '1170500022', 'Demitasse Spoon', 'Moka Spoon Gualtiero Marchesi St. steel 4 1/4"', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Broggi', 'Proepta', 'In Room Dining', 'PLAQUE', 18),
  ('747', 'BCFRSA13', 'Espresso Saucer', 'Fedra Saucer,Ø 13 cm / Ø 5 1/8”, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Rak', 'Proepta', 'In Room Dining', 'LOZA', 15),
  ('722', 'FW01', 'Bud Vase', 'Flower - Spring Vase Clear H11cm/H4.25in', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'LSA', NULL, 'In Room Dining', 'CRISTALERIA', 24),
  ('761', 'TBD', 'Tray Liner', 'Custom for Craster Tray and color to be selected dependign on interior design', (SELECT id FROM areas WHERE name = 'In Room Dinning' LIMIT 1), 'Chilewich', 'Proepta', 'In Room Dining', 'UTENSILIOS', 54),
  ('1290', 'T-16330-CHO', 'Coffee Urns 3 Gallons', 'URNA PARA CAFÉ 36.6 X 33 X 57.5 CM 12 LT ACERO INOXIDABLE ACENTOS Y PATAS CROMADAS ODIN', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 12),
  ('1281', '4383', 'Plate China', 'Pass arround cocktail -  plate “Modul”
 content in l
 0.07
 PU
 12 pcs
 china, white, rectangular, flat, for base trays “Modul” 
made of walnut and melamine l x w in cm
 PU
 22x11 
12 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'LOZA', 87),
  ('1262', 'DWELINPC', 'Power Cell Unit', 'Cordless warming induction range - 110volt.', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 10),
  ('1135', '171694; P2-F1-24-AGF413 Custom', 'Show Plate', 'Organic Shaped Plate in Almond SKU: 171694; P2-F1-24-AGF413 Custom to 30 cm diameter', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'My Glass Studio', 'Steelite', 'Banquet', 'LOZA', 280),
  ('1166', '53601S136', 'Water Pitcher', 'Water Pitcher w/Ice Guard, 1.5 qt, 7.125" x 4.5" x 8.125", Diva, Holloware, WNK, 18/10 Stainless, Stylish & Durable Hollowware (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'UTENSILIOS', 48),
  ('1183', 'B-V780520676', 'Stand for Bucket', 'BASE PARA CHAMPAÑERA  ACERO INOX MODERN 57 CM MODERN', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mepra', 'Proepta', 'Banquet', 'UTENSILIOS', 24),
  ('1277', '4381', 'Bowl China', 'Pass arround cocktail -  bowl “Modul”
 china, white, square, deep, for base trays “Modul” made 
of walnut and melamine
 11x11 
walnut with 
anti-slip mat', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'LOZA', 87),
  ('1151', 'RK-BACU28', 'Stackable Coffee Cup', 'TAZA CAFE APILABLE 9 1/2  OZ BANQUET', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 792),
  ('1291', 'B-V770552DCA', 'Coffee Urns 1.5 Gallons', 'URNA P/CAFE 7 LT 21 CM ACERO INOXIDABLE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 8),
  ('1267', '660143', 'Induction Shallow Cocotte', 'Induction Shallow Cocotte - Alabaster White - 31 cm D - 3.5 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 34),
  ('1131', '1170500001', 'Dinner Spoon', 'La Tavola - Table spoon Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792),
  ('1132', '1170500002', 'Dinner Fork', 'La Tavola - Table fork Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792),
  ('1133', '1170500005', 'Dinner Knife', 'La Tavola - Table knife Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792),
  ('1260', 'DW0499MBK', 'Single Heat Lamp Black', 'Modern Black Single Head Heat Lamp', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 12),
  ('1126', '1170500012', 'Appetizer Fork', 'La Tavola - Dessert fork Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792),
  ('1127', '1170500015', 'Appetizer Knife', 'La Tavola - Dessert knife Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792),
  ('1128', '1170500011', 'Appetizer/ Dessert Spoon', 'La Tavola - Dessert spoon Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792),
  ('1328', 'BGE-117649', 'Mobile Charcoal Grills Red', 'XLARGE BIG GREEN EGG 61cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Kamado Joe', 'Abastohotel', 'Banquet | Buffet Other', 'UTENSILIOS', 2),
  ('1129', '1170500021', 'Coffee/ Tea Spoon', 'La Tavola - Tea spoon Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 1318),
  ('1125', '305 05 09 562', 'Jam Presentation', '4-jar jam holder, Ø Cm (foro) 4,5', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'UTENSILIOS', 87),
  ('1326', 'CLML-3913-84', 'Service Cart Station', 'SIERRA CARRO MOVIL BEBIDAS 36x17.5x39"', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mogogo', 'Abastohotel', 'Banquet | Buffet Other', 'UTENSILIOS', 2),
  ('1201', '660412', 'Juice Dispenser', 'Juice dispenser with drip tray and M Riser - 8L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12),
  ('1139', 'RK-FDFP29', 'Flat Plate 11"', 'PLATO TRINCHE 29 CM FINE DINE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317),
  ('1136', 'BCSPCP15', 'B&B 6"', 'Spectra Coupe Plate, 5.9", bone china (24 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 792),
  ('1197', 'TBD', 'Off White Underlay - 72" Round Underlay  Table Cloth', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'UTENSILIOS', 84),
  ('1167', '53601S540', 'Coffee Pot', 'Double Wall Coffee Pot, 27.0 oz, 7.5" x 4.5" x 6.0", Diva, Holloware, WNK, 18/10 Stainless, Stylish & Durable Hollowware (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'UTENSILIOS', 36),
  ('1269', '660153', 'Induction Round Cocotte', 'Induction Round Cocotte - Alabaster White - Glass Cover 29 x 15.4 cm - 4L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 34),
  ('1124', '56591-24', 'Bread Presentation', 'Bowl/Tray, 9-9/20", round, with handles, dishwasher safe, 18/10 stainless steel, Sambonet, Sphera S/S (Special Order Item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Sambonet', 'Rosenthal Sambonet Paderno', 'Banquet', 'UTENSILIOS', 87),
  ('1172', '5557', 'Water Glass', 'VENETO TUMBLER ORANGE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Impulse', 'Impulse', 'Banquet', 'CRISTALERIA', 792),
  ('1182', 'B-V780520002', 'Bucket for Stand', 'CHAMPAÑERA ACERO INOXIDABLE  MODERN', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mepra', 'Proepta', 'Banquet', 'UTENSILIOS', 24),
  ('1155', 'RK-NNPR29', 'Coupe Plate 11"', 'PLATO COUPE 29 NANO', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317),
  ('1261', '2565-6', 'Sauce Marmite', 'Sauce Marmite 1-1/2 L # 
w/ Ladle and Tray Holder for fuel can
Mat: S/S', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Spring USA', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 6),
  ('1185', 'B-3050521513', 'Wine Coaster', 'BASE PARA VINO 12 CM DIA ACERO INOXIDABLE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mepra', 'Proepta', 'Banquet', 'UTENSILIOS', 116),
  ('1152', 'RK-BAST01', 'Coffee Saucer', 'PLATO P/TAZA Y TAZON 17 CM BANQUET', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 792),
  ('1198', 'TBD', 'Off White Overlay - 72"', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 168),
  ('1193', 'TBD', 'White Underlay - 72" Round Underlay Table Cloth', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 84),
  ('1159', 'RK-FDDC27', 'Coupe Deep Plate, 10.5"', 'ENSALADERA 1.5 LT 26 CM IVORY FINE DINE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267),
  ('1156', 'RK-NNPR27', 'Coupe Plate 10.5"', 'PLATO COUPE 27 CM NANO', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317),
  ('1279', '4032.G and cork  1501', 'Test Tube', 'Pass arround cocktail -  test tube and cork
 borosilicate glass (temperature change resistant), with 
flanged rim and round bottom, for holder for test tube 
item 4680.S and cork item 1501
 item Ø / height in cm content in l PU
 2/15 0.04 24 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 58),
  ('1258', '2.9.BLKOVAL.13', 'Cast Aluminum Mini Crock', 'FORTESSA - FORTALITE CASSOLETTE OVAL C/TAPA, ALUMINIO FUNDIDO, 16.5CM 340ML.', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Banquet | Miniatures', 'UTENSILIOS', 144),
  ('1173', 'RDL-0489/01', 'WINE', 'DEGUSTAZIONE COPA VINO BLANCO 340ml/11.3oz', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet', 'CRISTALERIA', 526),
  ('1174', 'RDL-0489/05', 'AP Wine 18oz', 'DEGUSTAZIONE COPA MISE EN PLACE 455ml/16oz', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet', 'CRISTALERIA', 526),
  ('1140', 'RK-FDGD29', 'Gourmet Deep Plate 11"', 'PLATO HONDO GOURMET 29 CM FINE DINE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 209),
  ('1138', 'BCSPDC23', 'Coupe Deep Plate, 9"', 'Spectra Coupe Deep Plate, 9.05", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267),
  ('1160', 'RK-FDGD26', 'Gourmet Deep Plate 10"', 'PLATO HONDO GOURMET 26 CM FINE DINE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267),
  ('1195', 'TBD', 'Off White Underlay - 66" Round Underlay  Table Cloth', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 60),
  ('1268', '660160', 'Induction Rectangular Dish', 'Induction Rectangular Dish - Alabaster White - 34 X 25 X 6.5 - 3.3 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 34),
  ('1194', 'TBD', 'White Overlay - 72"', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 168),
  ('1170', 'MTS012-BS', 'Tray Jack', 'Brushed Stainless steel tray jack with black leather straps', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Pantheon', 'Pantheon', 'Banquet', 'UTENSILIOS', 48),
  ('1379', 'VM5280BK-12', 'Bar Mat', 'Versa-Mat® Bar Mat Tile/Shelf Liner, 12" x 12", interlocking, easy to cut, raised surface for airflow, dishwasher safe, rubber, black, NSF', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'San Jamar', 'Sandolat', 'Banquet | BOH Bar', 'UTENSILIOS', 72),
  ('1157', 'RK-NNPR24', 'Coupe Plate, 9.5"', 'PLATO COUPE 24 CM NANO', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317),
  ('1259', '2.9.BLKPOT.13', 'Cast Aluminum Mini Crock', 'FORTESSA - FORTALITE CASSOLETTE REDONDO C/TAPA, ALUMINIO FUNDIDO, 13CM, 240ML.', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Banquet | Miniatures', 'UTENSILIOS', 144),
  ('1196', 'TBD', 'Off White Overlay - 66"', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 120),
  ('1137', 'BCSPCP21', 'Coupe Plate, 8"', 'Spectra Coupe Plate, 8.25", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267),
  ('1191', 'TBD', 'White Underlay - 66" Round Underlay  Table Cloth', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 60),
  ('1280', '4032.G', 'Holder for test tube', 'Pass arround cocktail -  holder for test tubes
 silicone, Ø 4.6 cm, 2.7 cm high, with grooves on the 
inside for easy insertion of glass tubes, for test tube 
 item colour PU
 4680.S black 6 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 58),
  ('1323', 'VCS-2448', 'Wire Shelving Set', 'Metro Shelf on Casters', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Winco', 'Mepsa', 'Banquet | Carts and Transport', 'UTENSILIOS', 8),
  ('1266', '660151', 'Induction Round Cocotte', 'Induction Round Cocotte - Alabaster white with glass cover - 26 cm D - 4 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 18),
  ('1192', 'TBD', 'White Overlay - 66"', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 120),
  ('1187', 'TBD', 'White Napkins', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 1584),
  ('1210', '656032', 'Display Wooden Tray 1', 'Wooden Box, 20-3/4"W x 12-3/4"D x 2-3/4"H, GN 1/1, maple', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 24),
  ('1188', 'TBD', 'Off White Napkins', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'YEKALON', 'Banquet  | Linen', 'BLANCOS', 1584),
  ('1123', '56770-00', 'Butter Presentation', 'Sambonet Bamboo Butter cup - 9,5 cm x 7,0 cm - Mirror Steel Stainless Steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Sambonet', 'Rosenthal Sambonet Paderno', 'Banquet', 'UTENSILIOS', 87),
  ('1168', '53601S139', 'Tea Pot', 'Single Wall Tea Pot L 5 1/4" W 3 3/8" H 4 7/8" (21 1/2 oz)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'LOZA', 36),
  ('1171', 'RK-UBCBVCL16P3', 'Plate Covers', 'CAMPANA P/PLATO HONDO GOURMET 16 CM BRAVURA *ACABADO ESPECIAL
SILVER*', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'RAK', 'Proepta', 'Banquet', 'LOZA', 108),
  ('1142', 'BCBVGD29', 'Gourmet Deep Plate 11"', 'Bravura Ø 29 cm - 31 cl. Ø 11 1/2” - 10 1/2 oz. 6', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 108),
  ('1312', '871557', 'Big Foot Door Wedge Rubber Grey', 'Door Stopper', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Wasserstrom', 'Sandolat', 'Banquet | Meeting Room and Miscelleanous', 'UTENSILIOS', 48),
  ('1246', 'DW724MWSS', 'Carving Board', 'CARVING BOARD 24 IN L X 18 IN W WOOD W/ FRAME AND MODERN FEET STAINLESS STEEL', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Display', 'UTENSILIOS', 4),
  ('1149', 'RK-FDCS35M', 'Soup Cup without Handle', 'TAZON CONSOME S/ASA 11 5/6 OZ 11 CM IVORY FINE DINE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 209),
  ('1331', '-', 'Couwboy Cauldron - Urban', 'https://cowboycauldron.com/products/the-urban-cowboy', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Couwboy Cauldron', 'Abastohotel', 'Banquet | Buffet Other', 'UTENSILIOS', 1),
  ('1158', 'RK-NNPR18', 'Coupe Plate, 7"', 'PLATO COUPE 18 CM NANO', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267),
  ('1145', 'BCBVCB50', 'Cereal Bowl', 'Bravura Low Cereal Bowl Ø 15 cm - 50 cl Ø 6” - 16 5/6 oz 12', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267),
  ('1200', '305 05 52 721', 'Honey Dispenser', 'Jambee jam/honey dispenser with wood base 23 oz', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 4),
  ('1271', '4583', 'Tray big', 'Pass arround cocktail -  95.5x28x1.8  base tray “Modul”
 melamine, black, surface matt, food-safe, dishwasher
safe, not suitable for microwave and combi steam oven', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 12),
  ('1144', 'BCPOPR28', 'Specialty Flat Coupe Plate 11"', 'Pose Flat Coupe Plate
28.8 x 27.1 cm
11 1/3” x 10 2/3”
12', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 144),
  ('1186', '2-1916-14B', 'Punch Bowl', 'Black Powder Coated Punch Bowl - Size 14" D', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'RCP', 'Steelite', 'Banquet', 'LOZA', 6),
  ('1176', 'V3872', 'Beer Glass', 'Arcoroc, Stemmed Beer Cervoise 12.5 Oz (H:7.0'''' T:2.56'''' M:3.0'''' B:2.75''''), [''Soda Lime Glass''], (24 PC In A Case), Minimum Purchasing Unit CS', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet', 'CRISTALERIA', 396),
  ('1239', 'BU_BD30NL', 'Bread Box - 3 Drawers', 'Oak 1.1 Bread Box: L: 349 x W: 530 x H: 190 mm (L: 13.7 × W: 20.9 × H: 7.4 in)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 4),
  ('1329', '-', 'Mobile Pizza Oven', 'Mobile Pizza Oven - Gozney Dome with Dome Stand and Dome Stand Cover. Peel and Turning Peel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Gozney', 'Gozney', 'Banquet | Buffet Other', 'UTENSILIOS', 1),
  ('1332', '-', 'Yakitori grill mill scale', 'https://millscale.co/products/yakitori-ii', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mill Scale', 'Mill Scale', 'Banquet | Buffet Other', 'UTENSILIOS', 1),
  ('1241', 'SET_GJO01', 'Mini Jar set Oak', 'Oak Mini Glass Jar set - Oak Mini Glass Jar set: L: 450 mm x W: 145 mm x H: 110 mm (L: 17.7 in x W: 5.7 in x H: 4.3 in)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8)
ON CONFLICT (code) DO UPDATE SET
  item_code = EXCLUDED.item_code,
  description = EXCLUDED.description,
  description_2 = EXCLUDED.description_2,
  area_id = EXCLUDED.area_id,
  brand_current = EXCLUDED.brand_current,
  supplier = EXCLUDED.supplier,
  category = EXCLUDED.category,
  item_type = EXCLUDED.item_type,
  qty_ordered = EXCLUDED.qty_ordered;
