-- ================================================
-- STEP 2: Items 1–300 of 2127
-- ================================================

INSERT INTO items (code, item_code, description, description_2, area_id, brand_current, supplier, category, item_type, qty_ordered, unit, price_unit, currency)
VALUES
  ('2084', '666M', 'Stand for Bucket', 'Less is more - mm. 1.2 - Wine Cooler Stand - H cm. 62 - cm 38x25 - H 24 2/5" - 15" x 9 7/8"', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mepra', 'Proepta', NULL, 'UTENSILIOS', 6, 'ea', 545.6077, 'USD'),
  ('2070', '82115AND0101V1', 'Plate 11.75"', 'Plate, 11.75" x 0.875", Signature, Diamond, William Edwards, Round, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 29, 'ea', 80.2036, 'USD'),
  ('2055', '82115AND0249', 'Ramekin and Butter Dish', 'William Edwards Diamond CONDIMENT POT D 6.5cm H 3.3cm (5.0cl) - D 2 1/2" H 1 3/8" (1 3/4oz)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 44, 'ea', 39.949, 'USD'),
  ('2066', '5428.04', 'Jam Presentation', 'Glass tray - clear glass, 4 deepenings (Ø 4.6 cm), for inserts and
portion jam up to Ø 4.4 cm (e.g. Darbo portion jam, 28 g
and 40 g) - l x w x h in cm PU 23.5x6.2x3', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Zieher', 'Latin Hotel', NULL, 'UTENSILIOS', 15, 'ea', 107.8, 'USD'),
  ('2083', '948', 'Bucket for Stand', 'Less is more - mm. 1.2 - Sparkling wine cooler for 3 bottles or 2 Magnum - cm. 35x15 - H cm. 18 - Lt. 9', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mepra', 'Proepta', NULL, 'UTENSILIOS', 6, 'ea', 300.1, 'USD'),
  ('2067', '82115AND0104', 'B&b 6.5"', 'Plate, 6.5" x 0.625", Signature, Diamond, William Edwards, Round, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 60, 'ea', 24.6722, 'USD'),
  ('2075', '82115AND0110', 'Coffee Cup', 'Tea Cup Can, 9.0 oz, 4.375" x 3.375" x 2.5", Signature, Diamond, William Edwards, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 48, 'ea', 28.2011, 'USD'),
  ('2076', '82115AND0211', 'Coffee Cup Saucer', 'Saucer, 6.375" x 0.875", Signature, Diamond, William Edwards, Round, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 48, 'ea', 25.7568, 'USD'),
  ('2069', '82115AND0102', 'Plate 10.75"', 'Plate, 10.75" x 0.875", Signature, Diamond, William Edwards, Round, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 29, 'ea', 42.1489, 'USD'),
  ('2072', '82115AND0136', 'Tray 13"', 'L/S Rectangle Tray, 13.375" x 6.0" x 0.75", Signature, Diamond, William Edwards, Rectangle, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 15, 'ea', 79.1495, 'USD'),
  ('2074', '82000AND0150', 'Bowl 9"', 'LARGE BOWL D 23.0cm H 8.2cm (2ltr)
D 9 1/8" H 3 1/4" (2 qt)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 29, 'ea', 38.1158, 'USD'),
  ('2073', '82000AND0550', 'Deep Coupe Bowl 11"', 'Studio William Whiteware Collection - DEEP COUPE BOWL D 28.5cm H 5.1cm (141.9cl)
D 11 1/4" H 2" (1 1/2 qt)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 29, 'ea', 37.4589, 'USD'),
  ('2149', 'VM5280BK-12', 'Bar Mat', 'Versa-Mat® Bar Mat Tile/Shelf Liner, 12" x 12", interlocking, easy to cut, raised surface for airflow, dishwasher safe, rubber, black, NSF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'San Jamar', 'Sandolat', NULL, 'UTENSILIOS', 18, 'ea', 65.7329, 'USD'),
  ('2068', '82115AND0103', 'Plate 8.75"', 'Plate, 8.75" x 0.625", Signature, Diamond, William Edwards, Round, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 29, 'ea', 34.648, 'USD'),
  ('2071', '82115AND0105', 'Bowl 8oz', 'Rim Bowl, 8.0 oz, 8.75" x 1.375", Signature, Diamond, William Edwards, Round, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 29, 'ea', 34.648, 'USD'),
  ('2054', '2522 STAINLESS STEEL', 'Bread Basket Op. 2 Large', 'Montenegro Bowl Large Gold - 7.3"Dx2.5"H', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Impulse', 'Impulse', NULL, 'UTENSILIOS', 26, 'ea', 42, 'USD'),
  ('2106', '20045622', 'Napkin Holder', 'Napkin Holder, 8-11/16" x 8-11/16, dishwasher safe, 18/10 stainless steel, STILE by Paninfarina  STOCK ITEM', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mepra', 'Mepsa', NULL, 'UTENSILIOS', 1, 'ea', 804.1419, 'USD'),
  ('2082', '82115AND0337', 'Tea Pot', 'OVAL TEAPOT 2 CUP L 23.4cm W 9.5cm H 10.0cm (55.0cl)
L 9 1/4" W 3 3/4" H 3 1/2" (19 3/8oz) , Signature, Diamond, William Edwards, Bone China  (minimum = case quantity, 6 each per case) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 12, 'ea', 66.1183, 'USD'),
  ('2053', '01001 CANVAS', 'Napkin', 'Eco Friendly - Canvas - WHITE - 80% COTTON – 20% LINEN - 826 CANVAS
HEM: Two Hems & Two Selvedges, 4 Hems, Mitred Corners,
Product ID: 1-G1-826', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Casa Rovea', 'Casa Rovea', NULL, 'BLANCOS', 120, 'ea', 4.78, 'EUR'),
  ('2077', '82115AND0112', 'Espresso Cup', 'Coffee Can, 3.5 oz, 3.25" x 2.25" x 2.5", Signature, Diamond, William Edwards, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24, 'ea', 26.7956, 'USD'),
  ('2078', '82115AND0152', 'Espresso Cup Saucer', 'Espresso Saucer, 4.75" x 0.75", Signature, Diamond, William Edwards, Round, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 24, 'ea', 22.8848, 'USD'),
  ('2080', '82115AND0335', 'Sugar Bowl', 'Oval Sugar Bowl, 8.0 oz, 4.0" x 2.375" x 3.5", Signature, Diamond, William Edwards, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 15, 'ea', 36.802, 'USD'),
  ('2079', '82115AND0340', 'Creamer', 'Milk Jug, 7.75 oz, 5.75" x 2.5" x 3.25", Signature, Diamond, William Edwards, Bone China (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'LOZA', 15, 'ea', 33.9452, 'USD'),
  ('2135', 'RA03', 'Cutting Board', 'Cutting Board, 24"W x 18"D x 2-1/4" thick, edge grain construction, Northern Hard Rock Maple, with Oil Finish, hand grips on each end, reversible', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'John Boos', 'John Boos', NULL, 'UTENSILIOS', 2, 'ea', 250, 'USD'),
  ('2097', '305 05 23 565', 'Beverage Tray', 'Round bar tray  Ø In 15', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Broggi', 'Proepta', NULL, 'UTENSILIOS', 6, 'ea', 83.286, 'USD'),
  ('2092', 'GM16P', 'Moscow Mule', 'Moscow Mule Mug, 16 oz., 3-1/4" dia. x 3-7/8"H, with brass handle, stainless steel, gold satin finish (hand wash only)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', NULL, 'CRISTALERIA', 24, 'ea', 20.2, 'USD'),
  ('2086', 'Z7310003', 'AP Wine Glass 14oz', 'Wine Glass, 14.25 oz., 3.5"W x 9.75"H, crystalline, Stolzle, Symphony (minimum = case quantity, 24 per case) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 36, 'ea', 11.1865, 'USD'),
  ('2099', 'V01 05 23 G11 M', 'Serving Tray', 'Gastronorm rectangular tray with handles Cm 53 x 32,5 (1/1)- In 20,7/8 x 12,3/4', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Broggi', 'Proepta', NULL, 'UTENSILIOS', 4, 'ea', 103.626, 'USD'),
  ('2089', 'Z1200019', 'Beer Glass', 'Beer Glass, 14 oz., 3" x 7-1/2", stemmed, Stolzle, Stemmed Beer, Soda Lime (minimum = case quantity, 24 per case) (Stock Item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 29, 'ea', 12.1225, 'USD'),
  ('2100', '5588 GLASS', 'Snack Presentation', 'Forest Snack Set of 3 - Glass - 3.5"D x 8" H - 6oz - 3 compartments', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Impulse', 'Impulse', NULL, 'UTENSILIOS', 12, 'ea', 32, 'USD'),
  ('2063', '54.7203.6049', 'Dinner Knife', 'Table Knife, 9-3/4", monobloc, 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 48, 'ea', 6.8, 'USD'),
  ('2085', '12635/01', 'Water Glass', 'Double Old Fashioned Glass, 12.25 oz., pure and transparent, durable, break resistant, heat treated, machine-blown SPARKX® lead-free crystal glass, Top Class by Luigi Bormioli (Core collection)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'CRISTALERIA', 72, 'ea', 4.476, 'USD'),
  ('2108', 'RBB02', 'Silicone Bands', 'Band, 1/2"D, silicone, blue, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2109', 'RBP01', 'Silicone Bands', 'Band, 1/2"D, silicone, pink, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2110', 'RBY03', 'Silicone Bands', 'Band, 1/2"D, silicone, yellow, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2111', 'RBDG3', 'Silicone Bands', 'Band, 1/2"D, silicone, green, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2112', 'RBO05', 'Silicone Bands', 'Band, 1/2"D, silicone, orange, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2113', 'RBW06', 'Silicone Bands', 'Band, 1/2"D, silicone, white, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2114', 'RBR09', 'Silicone Bands', 'Band, 1/2"D, silicone, red, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2115', 'RBB06', 'Silicone Bands', 'Band, 1/2"D, silicone, black, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2116', 'RBBR7', 'Silicone Bands', 'Band, 1/2"D, silicone, brown, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('2105', '22918-4-116', 'Condiment Caddy', '3 Jar Display, 13-1/2"W x 5"D x 4-3/4"H, includes (3) oval glass jars 16 oz., plated metal, gold, Monaco', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', NULL, 'UTENSILIOS', 2, 'ea', 179.66, 'USD'),
  ('2087', 'Z7310000', 'Specialty Wine Glass 25oz', 'Burgundy Glass, 25 oz., 4-1/2" x 9-3/4", Symphony, Stolzle, Crystalline (minimum = case quantity, 24 per case) (Stock Item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Stolzle', 'Proepta', NULL, 'CRISTALERIA', 24, 'ea', 12.1225, 'USD'),
  ('2061', '54.7201.6040', 'Tablespoon', 'Table Spoon, 9", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 48, 'ea', 5.9, 'USD'),
  ('2062', '54.7202.6040', 'Dinner Fork', 'Table Fork, 9", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 48, 'ea', 5.9, 'USD'),
  ('2057', '54.7206.6049', 'Appetizer Knife', 'Dessert Knife, 9", monobloc, 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 48, 'ea', 5.8, 'USD'),
  ('2102', 'UR90210', 'Syphon', 'Syphon, 1.0 qt, 4.75" x 14.625"H, stainless steel, gold, Utopia, Syphons (minimum = case quantity) (stock item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'UTENSILIOS', 1, 'ea', 319.579, 'USD'),
  ('2093', '13142/01', 'Gin & Tonic', 'Gin Glass, 25.3 oz., 4.1" dia. x 9.1"H, SON.hyx® lead-free crystal glass, Speakeasy Swing by Luigi Bormioli', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'CRISTALERIA', 24, 'ea', 11.94, 'USD'),
  ('2059', '54.7207.6040', 'Coffee / Teaspoon', 'Tea/Coffee Spoon, 5-1/2", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 72, 'ea', 3.4, 'USD'),
  ('2056', '54.7205.6040', 'Appetizer Fork', 'Dessert Fork, 8-1/4", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 48, 'ea', 5, 'USD'),
  ('2058', '54.7204.6040', 'Appetizer Spoon', 'Dessert Spoon, 8-1/4", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 48, 'ea', 5, 'USD'),
  ('2065', '54.7266.6049', 'Butter Knife / Spreader', 'Butter Knife, 6-3/4", monobloc, 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 48, 'ea', 4.9, 'USD'),
  ('2094', '13168/01', 'Martini', 'Martini Glass, 7.4 oz., 3.9" dia. x 5.9"H, SON.hyx® lead-free crystal glass, Speakeasy Swing by Luigi Bormioli (Core collection)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'CRISTALERIA', 24, 'ea', 10.38, 'USD'),
  ('2081', '82115AND0341', 'Sugar Bowl Lid', 'Oval Covered Sugar Lid, 4.125" x 2.875" x 1.0", Signature, Diamond, William Edwards, Bone China  (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'UTENSILIOS', 15, 'ea', 12.9242, 'USD'),
  ('2091', '13143/01', 'High Ball', 'Hi-Ball Glass, 19.2 oz., 3.4" dia. x 5.5"H, SON.hyx® lead-free crystal glass, Speakeasy Swing by Luigi Bormioli (Core collection)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'CRISTALERIA', 29, 'ea', 6.14, 'USD'),
  ('2095', '13192/01', 'Snifter', 'Snifter Glass, 15.7 oz., 3.7" dia. x 5.0"H, SON.hyx® lead-free crystal glass, Speakeasy Swing by Luigi Bormioli (Core collection)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'CRISTALERIA', 24, 'ea', 8.39, 'USD'),
  ('2101', 'HGBDV100-001', 'Atomizer Sprayer', 'Legend Glassware - Eros Atomizer, 3.5 oz., premium glass (1 each per case)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Hospitality Brands', 'Latin Hotel', NULL, 'UTENSILIOS', 6, 'ea', 32.9, 'USD'),
  ('2090', '13191/01', 'Rock Glass', 'DOF Glass, 15.2 oz., 3.6" dia. x 3.9"H, SON.hyx® lead-free crystal glass, Speakeasy Swing by Luigi Bormioli (Core collection)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'CRISTALERIA', 29, 'ea', 5.79, 'USD'),
  ('2132', 'JP9730', 'Juicer, Lever / Crank Type', 'Cash & Carry Big Squeeze™ Juice Press, 11-1/2" x 7" x 17", manual, accommodates 5-3/4" glass, 3-pinion design, hand wash only, 18/8 stainless steel cone, cast iron construction, black coated finish, NSF (1 each minimum order)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', NULL, 'UTENSILIOS', 1, 'ea', 175.87, 'USD'),
  ('2126', 'M37204GD', 'Bar Spoon', 'Barfly® Diamond Lattice Japanese Style Bar Spoon, 13-3/16" (33.5 cm), machined end, twisted stem, one-piece, 18/8 stainless steel, gold-plated finish', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 4, 'ea', 43.1043, 'USD'),
  ('2088', 'U1051', 'Champagne Glass', 'Chef & Sommelier  Open Up 6.75 oz. Flute Glass by Arc Cardinal', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Chef and Sommelier', 'Proepta', NULL, 'CRISTALERIA', 29, 'ea', 5.04, 'USD'),
  ('2098', '305 12 27 503', 'Beverage Tray Non Slip Mat', 'Non-slip mat for beverage/ bar tray  Ø In  15', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Broggi', 'Proepta', NULL, 'UTENSILIOS', 6, 'ea', 28.356, 'USD'),
  ('2147', 'SI6000', 'Ice Tote', 'Saf-T-Ice® Tote, 6 gallon, polycarbonate, rubber handle, with tri-grip feature, includes Saf-T-Ice® HACCP hanger for elevation to waist level, NSF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'San Jamar', 'Sandolat', NULL, 'UTENSILIOS', 3, 'ea', 44.9372, 'USD'),
  ('2139', '1851-5', 'Storage Jar / Ingredient Canister, Glass', 'Mixology Jar, 32 oz. capacity, 5-1/4" dia., x 4-1/2"H, double walled insulated base, stainless steel solid lid with silicone lining, glass, clear (cold pucks sold separately)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', NULL, 'UTENSILIOS', 3, 'ea', 41.19, 'USD'),
  ('2121', 'M37199GD', 'Cocktail Shaker 28oz', 'Barfly® Diamond Lattice Shaker, 28 oz., 3-5/8" dia. x 7"H, capped bottom, 18/8 stainless steel, satin finish interior, gold-plated exterior finish, intricate etched pattern design', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 2, 'ea', 50.779, 'USD'),
  ('2123', 'M37203GD', 'Bar Strainer', 'Barfly® Diamond Lattice Spring Bar Strainer, 6" overall length, heavy duty, 2-prong, replaceable spring, hanging hole, 18/8 stainless steel, gold-plated finish', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 2, 'ea', 48.6763, 'USD'),
  ('2137', '1851-4', 'Storage Jar / Ingredient Canister, Glass', 'Mixology Jar, 16 oz. capacity, 4-1/4" dia. x 4"H, double walled insulated base, stainless steel solid lid with silicone lining, glass, clear (cold pucks sold separately)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', NULL, 'UTENSILIOS', 3, 'ea', 28.36, 'USD'),
  ('2107', '3308-110', 'Straw Holder', 'Aspen Stir Stick Organizer I 5.25” W x 5.25” D x 5.5” H', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', NULL, 'UTENSILIOS', 1, 'ea', 83.54, 'USD'),
  ('2120', 'M37005GD', 'Jigger', 'Barfly® Japanese Style Jigger, 1 & 2 oz., with internal marking lines, 18/8 stainless steel, gold-plated finish', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 3, 'ea', 27.4396, 'USD'),
  ('2122', 'M37198GD', 'Cocktail Shaker 18oz', 'Barfly® Diamond Lattice Shaker, 18 oz., 3-1/2" dia. x 5"H, capped bottom, 18/8 stainless steel, satin finish interior, gold-plated exterior finish, intricate etched pattern design', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 2, 'ea', 40.8965, 'USD'),
  ('2060', '54.7209.6040', 'Demitasse Spoon', 'Demitasse Spoon, 4-1/4", 18/10 stainless steel, Nordic by WMF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'WMF', 'Latin Hotel', NULL, 'PLAQUE', 24, 'ea', 2.9, 'USD'),
  ('2130', '285-50', 'Liquor Pourer', 'Spill-Stop® Tapered Pourer, seamless spout, with poly-kork, controlled medium speed, chrome, Made in USA (packed one dozen per poly bag, one gross per carton = 144 each, minimum order 1 gross)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Spill-Stop', 'Spill-Stop', NULL, 'UTENSILIOS', 29, 'ea', 2.28, 'USD'),
  ('2064', 'WL830527', 'Steak Knife', 'Jumbo Hvy Duty Steak Knife 25.4 cm (10.0")', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'PLAQUE', 12, 'ea', 4.7358, 'USD'),
  ('2051', '82000AND0124', 'Salt Mill', 'SALT H 6.7cm H 2 5/8" William Edwards Whiteware Collection', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'UTENSILIOS', 6, 'ea', 10.0675, 'USD'),
  ('2052', '82000AND0125', 'Pepper Mill', 'PEPPER H 6.7cm H 2 5/8" William Edwards Whiteware Collection', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Steelite', 'Steelite', NULL, 'UTENSILIOS', 6, 'ea', 10.0675, 'USD'),
  ('2124', 'M37028GD', 'Julep Strainer', 'Barfly® Julep Strainer, 6-1/2" overall length, welded handle with hanging hole, 18/8 stainless steel, gold-plated finish', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 2, 'ea', 29.6473, 'USD'),
  ('2140', '1851-5PUCK', 'Ice Pack', 'Cooling Puck, black (for 1851-5 jar)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', NULL, 'UTENSILIOS', 3, 'ea', 16.69, 'USD'),
  ('2142', 'BM-1812K', 'Bar Mat', 'Service Mat, 18" x 12", rubber, black, NSF (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Winco', 'Equipo Hotel', NULL, 'UTENSILIOS', 3, 'ea', 15.94, 'USD'),
  ('2125', 'M37025GD', 'Mesh Strainer', 'Barfly® Mesh Strainer, 3-1/2" dia. bowl, 10-3/8" overall length, fine-mesh, front rest loop, rod handle, 18/8 stainless steel, gold-plated finish', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 2, 'ea', 21.3419, 'USD'),
  ('2134', 'M15500', 'Channel Knife', 'Mercer Cutlery Channel Knife, stain-resistant steel, molded slip-resistant polypropylene handle', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 2, 'ea', 20.5008, 'USD'),
  ('2145', '160-02', 'Bar Mat', 'Bar Mat, 24"L x 3-1/4"W x 1/2"H, non-slip, rubber, black', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Spill-Stop', 'Spill-Stop', NULL, 'UTENSILIOS', 4, 'ea', 9.08, 'USD'),
  ('2138', '1851-4PUCK', 'Ice Pack', 'Cooling Puck, black (for 1851-4 jar)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', NULL, 'UTENSILIOS', 3, 'ea', 11.86, 'USD'),
  ('2096', '13190/01', 'Specialty Champagne Coupe', 'Champagne Coupe Glass, 10.1 oz., 4.2" dia. x 5.8"H, SON.hyx® lead-free crystal glass, Speakeasy Swing by Luigi Bormioli (Core collection)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'CRISTALERIA', 3, 'ea', 10.24, 'USD'),
  ('2117', '12273/02', 'Bitter / Dash Bottle', '10 cl - 3 ½ oz h 14.2 cm - 5 5⁄8” Max Ø 5.2 cm - 2”', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'UTENSILIOS', 3, 'ea', 9.984, 'USD'),
  ('2118', '12272/02', 'Bitter / Dash Bottle', '10 cl - 3 ½ oz h 13.5 cm - 5 3 ⁄8” Max Ø 5.7 cm - 2 ¼”', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Luigi Bormioli', 'Proepta', NULL, 'UTENSILIOS', 3, 'ea', 9.984, 'USD'),
  ('2119', '301-02', 'Drink Bar Mix Pourer Lid', 'Dust Cap, 1/2" L, for pour spouts (285-50 & 282-50), Made in USA (one gross per poly bag, one gross per carton = 144 each, minimum order one gross)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Spill-Stop', 'Spill-Stop', NULL, 'UTENSILIOS', 1, 'pk', 28.8, 'USD'),
  ('2141', 'M37023', 'Citrus Squeezer', 'Barfly Juicer, 8-7/8", with stainless steel pin, cast aluminum', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 1, 'ea', 24.1805, 'USD'),
  ('2143', 'CAP07', 'Bar Knife', 'Ellis Bar Knife, 9" overall, 4-1/2" blade, stainless steel blade, POM handle, Arcoroc, Mix', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 2, 'ea', 9.88, 'USD'),
  ('2152', 'CHBST112', 'Bottle Stopper', 'Champagne Bottle "Popper-Stopper", stainless steel', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', NULL, 'UTENSILIOS', 2, 'ea', 9.22, 'USD'),
  ('2127', 'CAP09', 'Muddler', 'Muddler, 9-5/8", stainless steel, Arcoroc, Mix', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 2, 'ea', 9.07, 'USD'),
  ('2103', 'FP332', 'Mixing Glass', 'Arcoroc, Broadway Mixing Beaker 24.0 Oz (H:6.0'''' T:4.38'''' M:4.38'''' B:3.63''''), [''Soda Lime Glass''], (6 PC In A Case), Minimum Purchasing Unit CS
Dimensions 6(h) x 4.37(w) x 4.37(d)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 2, 'ea', 8.96, 'USD'),
  ('2128', 'CAP01', 'Tongs, Tweezer', 'Tweezers, 6-1/4", stainless steel, Arcoroc, Mix', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cardinal', 'Proepta', NULL, 'UTENSILIOS', 4, 'ea', 3.99, 'USD'),
  ('2154', 'GR-3', 'Salt Rimmer', 'Glass Rimmer / Margarita Salter with 3 Compartments', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Winco', 'Equipo Hotel', NULL, 'UTENSILIOS', 1, 'ea', 13.11, 'USD'),
  ('2150', '7770-C', 'Bottle Stopper', 'VacuVin® Vacuum Wine Preservation, includes: (1) 5" x 2-7/8" white pump, (1) 1-3/4" long gray stopper (carded)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Franmara', 'Franmara', NULL, 'UTENSILIOS', 2, 'ea', 6.5, 'USD'),
  ('2148', 'AS-12', 'Scoop', 'Scoop, 12 oz., aluminum (hand wash only) (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Winco', 'Equipo Hotel', NULL, 'UTENSILIOS', 3, 'ea', 4.28, 'USD'),
  ('2146', '100MCCW135', 'Measuring Cup', 'Camwear® Measuring Cup, 1 qt., molded handle, dishwasher safe, polycarbonate, clear, NSF', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Cambro', 'Equipo Hotel', NULL, 'UTENSILIOS', 1, 'ea', 9.53, 'USD'),
  ('2104', '2.5.003.00.277', 'Ice Tongs', 'Ice/Sugar Tong 6” (15cm)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Fortessa', 'Hotel Depot', NULL, 'UTENSILIOS', 2, 'ea', 4.71, 'USD'),
  ('2144', 'SS-821', 'Sharpening Stone', 'Sharpening Stone, 8" x 2" x 1"H, rectangular, fine/medium grain, carbonized silicone (Qty Break = 12 each)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Winco', 'Equipo Hotel', NULL, 'UTENSILIOS', 1, 'ea', 8.93, 'USD'),
  ('2153', 'E5604', 'Lemon Lime Zester', 'Cash & Carry FirmGrip® Zester/Lemon Peeler, 5-3/4" x 1-1/8" x 7/8", dishwasher safe, ergonomic soft grip handle, stainless steel, black (individually carded) (1 each minimum order)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', NULL, 'UTENSILIOS', 2, 'ea', 4.4, 'USD'),
  ('2129', 'M33071BKB', 'Vegetable Peeler, Manual', 'Y-Peeler, 4" overall length, swivel blade, high-carbon steel, black handle', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Mercer', 'Mepsa', NULL, 'UTENSILIOS', 1, 'ea', 6.3079, 'USD'),
  ('2151', '7771-C', 'Bottle Stopper', 'VacuVin® Vacuum Wine Stopper, 1-3/4" long, ABS plastic, gray (2 each per pack) (carded)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Franmara', 'Franmara', NULL, 'UTENSILIOS', 2, 'ea', 3, 'USD'),
  ('2155', 'WCS871', 'Wine Key', 'Waiters Corkscrew - 4-1/2″ L x 7/8″ W x 7/8" - Stainless Steel', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', NULL, 'UTENSILIOS', 2, 'ea', 2.85, 'USD'),
  ('2133', '396', 'Bottle Opener', 'Pocket Bottle Opener, 7" flat, dishwasher safe, stainless steel (1 each minimum order)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', NULL, 'UTENSILIOS', 3, 'ea', 1.63, 'USD'),
  ('2136', 'PF-32', 'Funnel', 'Funnel, 32 oz., 6-1/4" dia., round, plastic, white (Qty Break = 6 each)', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Winco', 'Equipo Hotel', NULL, 'UTENSILIOS', 1, 'ea', 2.05, 'USD'),
  ('2131', '186700', 'Mandoline', 'Benriner "Little Beni" Mandoline Slicer, 12-1/2"L x 3-1/2"W, includes (3) blades and safety pusher, stainless steel blades, polypropylene, made in Japan', (SELECT id FROM areas WHERE name = '5th Resident Lounge' LIMIT 1), 'Matfer', 'Mepsa', NULL, 'UTENSILIOS', 1, 'ea', 0, 'USD'),
  ('1290', 'DW43WBKSS', 'Coffee Urns 3 Gallons', 'Tempo Fuel Coffee Urn  L 14" W 14" H 23" (3 gal) (11.4 L)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 12, 'ea', 1453.1367, 'USD'),
  ('1281', '4383', 'Plate China', 'Pass arround cocktail -  plate “Modul”
 content in l
 0.07
 PU
 12 pcs
 china, white, rectangular, flat, for base trays “Modul” 
made of walnut and melamine l x w in cm
 PU
 22x11 
12 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'LOZA', 87, 'ea', 162.3, 'USD'),
  ('1262', 'DWELINPC', 'Power Cell Unit', 'Cordless warming induction range - 110volt.', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 10, 'ea', 1621.9921, 'USD'),
  ('1135', '171694; P2-F1-24-AGF413 Custom', 'Show Plate', 'Organic Shaped Plate in Almond SKU: 171694; P2-F1-24-AGF413 Custom to 30 cm diameter', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'My Glass Studio', 'Steelite', 'Banquet', 'LOZA', 280, 'ea', 75.9719, 'USD'),
  ('1166', '53601S136', 'Water Pitcher', 'Water Pitcher w/Ice Guard, 1.5 qt, 7.125" x 4.5" x 8.125", Diva, Holloware, WNK, 18/10 Stainless, Stylish & Durable Hollowware (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'UTENSILIOS', 48, 'ea', 297.2157, 'USD'),
  ('1183', '666M', 'Stand for Bucket', 'Less is more - mm. 1.2 - Wine Cooler Stand - H cm. 62 - cm 38x25 - H 24 2/5" - 15" x 9 7/8"', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mepra', 'Proepta', 'Banquet', 'UTENSILIOS', 24, 'ea', 545.6077, 'USD'),
  ('1277', '4381', 'Bowl China', 'Pass arround cocktail -  bowl “Modul”
 china, white, square, deep, for base trays “Modul” made 
of walnut and melamine
 11x11 
walnut with 
anti-slip mat', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'LOZA', 87, 'ea', 117, 'USD'),
  ('1151', 'BCFRSC28', 'Stackable Coffee Cup', 'Fedra Stackable Coffee Cup, Ht. 6 cm - 29 cl Ht. 2 2/5” - 9 4/5 oz 12', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 792, 'ea', 10.584, 'USD'),
  ('1291', 'DW41WBKSS', 'Coffee Urns 1.5 Gallons', 'Tempo Fuel Coffee Urn L 13" W 12" H 18 3/4" (1 1/2 gal) (5.7 L)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 8, 'ea', 1216.1007, 'USD'),
  ('1267', '660143', 'Induction Shallow Cocotte', 'Induction Shallow Cocotte - Alabaster White - 31 cm D - 3.5 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 34, 'ea', 275.565, 'USD'),
  ('1131', '1170500001', 'Dinner Spoon', 'La Tavola - Table spoon Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792, 'ea', 9.966, 'USD'),
  ('1132', '1170500002', 'Dinner Fork', 'La Tavola - Table fork Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792, 'ea', 9.966, 'USD'),
  ('1133', '1170500005', 'Dinner Knife', 'La Tavola - Table knife Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792, 'ea', 9.792, 'USD'),
  ('1260', 'DW0499MBK', 'Single Heat Lamp Black', 'Modern Black Single Head Heat Lamp', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 12, 'ea', 722.2144, 'USD'),
  ('1126', '1170500012', 'Appetizer Fork', 'La Tavola - Dessert fork Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792, 'ea', 9.06, 'USD'),
  ('1127', '1170500015', 'Appetizer Knife', 'La Tavola - Dessert knife Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792, 'ea', 9.06, 'USD'),
  ('1128', '1170500011', 'Appetizer/ Dessert Spoon', 'La Tavola - Dessert spoon Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 792, 'ea', 9.06, 'USD'),
  ('1328', 'KJ15041021', 'Mobile Charcoal Grills Red', 'Big Joe III w/ Cart, Hyperbolic Insert, Aluminum Side Shelves, Heat Def, D&C, Tools', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Kamado Joe', 'Abastohotel', 'Banquet | Buffet Other', 'UTENSILIOS', 2, 'ea', 4124.9875, 'USD'),
  ('1129', '1170500021', 'Coffee/ Tea Spoon', 'La Tavola - Tea spoon Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 1318, 'ea', 5.328, 'USD'),
  ('1125', '305 05 09 562', 'Jam Presentation', '4-jar jam holder, Ø Cm (foro) 4,5', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'UTENSILIOS', 87, 'ea', 80.784, 'USD'),
  ('1326', 'MGCRNX11MBXX - Finishes TBD', 'Service Cart Station', 'Service Cart w/Leather Handle And Heavy Duty Bumper L 42 1/2" W 24" H 36 1/2"', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mogogo', 'Abastohotel', 'Banquet | Buffet Other', 'UTENSILIOS', 2, 'ea', 2065.2516, 'USD'),
  ('1201', '660412', 'Juice Dispenser', 'Juice dispenser with drip tray and M Riser - 8L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 658.785, 'USD'),
  ('1139', 'BCFRFP29', 'Flat Plate 11"', 'Fedra Round flat plates with rim Ø 29 cm / Ø 11 1/2” 12', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317, 'ea', 21.156, 'USD'),
  ('1136', 'BCSPCP15', 'B&B 6"', 'Spectra Coupe Plate, 5.9", bone china (24 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 792, 'ea', 8.394, 'USD'),
  ('1197', 'TBD', 'Off White Underlay - 72" Round Underlay  Table Cloth', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'UTENSILIOS', 84, 'ea', 91.94, 'USD'),
  ('1167', '53601S540', 'Coffee Pot', 'Double Wall Coffee Pot, 27.0 oz, 7.5" x 4.5" x 6.0", Diva, Holloware, WNK, 18/10 Stainless, Stylish & Durable Hollowware (minimum = case quantity) (STOCK item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'UTENSILIOS', 36, 'ea', 210.542, 'USD'),
  ('1269', '660153', 'Induction Round Cocotte', 'Induction Round Cocotte - Alabaster White - Glass Cover 29 x 15.4 cm - 4L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 34, 'ea', 222.895, 'USD'),
  ('1124', '56591-24', 'Bread Presentation', 'Bowl/Tray, 9-9/20", round, with handles, dishwasher safe, 18/10 stainless steel, Sambonet, Sphera S/S (Special Order Item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Sambonet', 'Rosenthal Sambonet Paderno', 'Banquet', 'UTENSILIOS', 87, 'ea', 73.21, 'USD'),
  ('1172', '5557', 'Water Glass', 'VENETO TUMBLER ORANGE', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Impulse', 'Impulse', 'Banquet', 'CRISTALERIA', 792, 'ea', 7.85, 'USD'),
  ('1182', '948', 'Bucket for Stand', 'Less is more - mm. 1.2 - Sparkling wine cooler for 3 bottles or 2 Magnum - cm. 35x15 - H cm. 18 - Lt. 9', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mepra', 'Proepta', 'Banquet', 'UTENSILIOS', 24, 'ea', 300.1, 'USD'),
  ('1155', 'BCFRCP29', 'Coupe Plate 11"', 'Fedra Coupe Plate, 11.4", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317, 'ea', 17.472, 'USD'),
  ('1261', '2565-6', 'Sauce Marmite', 'Sauce Marmite 1-1/2 L # 
w/ Ladle and Tray Holder for fuel can
Mat: S/S', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Spring USA', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 6, 'ea', 1075.41, 'USD'),
  ('1185', '200443', 'Wine Coaster', 'STILE living by Pininfarina COASTER', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mepra', 'Proepta', 'Banquet', 'UTENSILIOS', 116, 'ea', 46.2581, 'USD'),
  ('1152', 'BCFRSA17', 'Coffee Saucer', 'Fedra Saucer, Ø 17.5 cm / Ø 6 4/5”, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 792, 'ea', 6.744, 'USD'),
  ('1198', 'TBD', 'Off White Overlay - 72"', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 168, 'ea', 37.01, 'USD'),
  ('1193', 'TBD', 'White Underlay - 72" Round Underlay Table Cloth', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 84, 'ea', 73.21, 'USD'),
  ('1159', 'BCFRDC27', 'Coupe Deep Plate, 10.5"', 'Fedra Coupe Deep Plate, 10.63", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 19.224, 'USD'),
  ('1156', 'BCFRCP27', 'Coupe Plate 10.5"', 'Fedra Coupe Plate, 10.63", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317, 'ea', 15.636, 'USD'),
  ('1279', '4032.G and cork  1501', 'Test Tube', 'Pass arround cocktail -  test tube and cork
 borosilicate glass (temperature change resistant), with 
flanged rim and round bottom, for holder for test tube 
item 4680.S and cork item 1501
 item Ø / height in cm content in l PU
 2/15 0.04 24 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 58, 'ea', 83.2, 'USD'),
  ('1258', '2.9.BLKOVAL.13', 'Cast Aluminum Mini Crock', 'FORTESSA - FORTALITE CASSOLETTE OVAL C/TAPA, ALUMINIO FUNDIDO, 16.5CM 340ML.', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Banquet | Miniatures', 'UTENSILIOS', 144, 'ea', 33.24, 'USD'),
  ('1173', '26.112415', 'Champagne Glass', 'Zwiesel Glass Pure Champagne Flute Glass, (7) 7.1 oz., dishwasher safe, lead free, sheer rim, crystal glass (0.3 each weight) (Per case = 6 each) (ecomm dealers 4 case increments; special box will be added cost)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet', 'CRISTALERIA', 526, 'ea', 8.95, 'USD'),
  ('1174', '26.112413', 'AP Wine 18oz', 'Zwiesel Glass Pure Cabernet Glass, (1) 18.2 oz., dishwasher safe, lead free, sheer rim, crystal glass (0.38 each weight) (Per case = 6 each) (ecomm dealers 4 case increments; special box will be added cost)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet', 'CRISTALERIA', 526, 'ea', 8.95, 'USD'),
  ('1140', 'BCFRGD29', 'Gourmet Deep Plate 11"', 'Fedra Gourmet Deep Plate, 11.4", bone china (6 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 209, 'ea', 22.032, 'USD'),
  ('1138', 'BCSPDC23', 'Coupe Deep Plate, 9"', 'Spectra Coupe Deep Plate, 9.05", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 17.13, 'USD'),
  ('1160', 'BCFRGD26', 'Gourmet Deep Plate 10"', 'Fedra Gourmet Deep Plate, 10.24", bone china (6 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 17.1, 'USD'),
  ('1195', 'TBD', 'Off White Underlay - 66" Round Underlay  Table Cloth', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 60, 'ea', 87.52, 'USD'),
  ('1268', '660160', 'Induction Rectangular Dish', 'Induction Rectangular Dish - Alabaster White - 34 X 25 X 6.5 - 3.3 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 34, 'ea', 146.315, 'USD'),
  ('1194', 'TBD', 'White Overlay - 72"', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 168, 'ea', 28.98, 'USD'),
  ('1170', 'MTS012-BS', 'Tray Jack', 'Brushed Stainless steel tray jack with black leather straps', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Pantheon', 'Pantheon', 'Banquet', 'UTENSILIOS', 48, 'ea', 99.84, 'USD'),
  ('1379', 'VM5280BK-12', 'Bar Mat', 'Versa-Mat® Bar Mat Tile/Shelf Liner, 12" x 12", interlocking, easy to cut, raised surface for airflow, dishwasher safe, rubber, black, NSF', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'San Jamar', 'Sandolat', 'Banquet | BOH Bar', 'UTENSILIOS', 72, 'ea', 65.7329, 'USD'),
  ('1157', 'BCFRCP24', 'Coupe Plate, 9.5"', 'Fedra Coupe Plate, 9.45", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 317, 'ea', 12.42, 'USD'),
  ('1259', '2.9.BLKPOT.13', 'Cast Aluminum Mini Crock', 'FORTESSA - FORTALITE CASSOLETTE REDONDO C/TAPA, ALUMINIO FUNDIDO, 13CM, 240ML.', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Banquet | Miniatures', 'UTENSILIOS', 144, 'ea', 26.69, 'USD'),
  ('1196', 'TBD', 'Off White Overlay - 66"', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 120, 'ea', 37.01, 'USD'),
  ('1137', 'BCSPCP21', 'Coupe Plate, 8"', 'Spectra Coupe Plate, 8.25", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 13.326, 'USD'),
  ('1191', 'TBD', 'White Underlay - 66" Round Underlay  Table Cloth', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 60, 'ea', 67.96, 'USD'),
  ('1280', '4032.G', 'Holder for test tube', 'Pass arround cocktail -  holder for test tubes
 silicone, Ø 4.6 cm, 2.7 cm high, with grooves on the 
inside for easy insertion of glass tubes, for test tube 
 item colour PU
 4680.S black 6 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 58, 'ea', 58.7, 'USD'),
  ('1323', 'VCS-2448', 'Wire Shelving Set', 'Metro Shelf on Casters', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Winco', 'Mepsa', 'Banquet | Carts and Transport', 'UTENSILIOS', 8, 'ea', 466.6523, 'USD'),
  ('1266', '660151', 'Induction Round Cocotte', 'Induction Round Cocotte - Alabaster white with glass cover - 26 cm D - 4 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 18, 'ea', 197.885, 'USD'),
  ('1192', 'TBD', 'White Overlay - 66"', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 120, 'ea', 28.98, 'USD'),
  ('1187', 'TBD', 'White Napkins', 'Cotton - Patern Organic All Over White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 1584, 'ea', 1.85, 'USD'),
  ('1210', '656032', 'Display Wooden Tray 1', 'Wooden Box, 20-3/4"W x 12-3/4"D x 2-3/4"H, GN 1/1, maple', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 24, 'ea', 142.02, 'USD'),
  ('1188', 'TBD', 'Off White Napkins', 'Cotton - Patern Mini Natte Off White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 1584, 'ea', 1.82, 'USD'),
  ('1123', '56770-00', 'Butter Presentation', 'Sambonet Bamboo Butter cup - 9,5 cm x 7,0 cm - Mirror Steel Stainless Steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Sambonet', 'Rosenthal Sambonet Paderno', 'Banquet', 'UTENSILIOS', 87, 'ea', 32.87, 'USD'),
  ('1168', '53601S139', 'Tea Pot', 'Single Wall Tea Pot L 5 1/4" W 3 3/8" H 4 7/8" (21 1/2 oz)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'LOZA', 36, 'ea', 90.6909, 'USD'),
  ('1171', 'Crome Custom', 'Plate Covers', 'For Gourmet Plate Large Well
D 11 1/4" and  Bowl 11"', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'RAK', 'Proepta', 'Banquet', 'LOZA', 108, 'ea', 24.9, 'USD'),
  ('1142', 'BCBVGD29', 'Gourmet Deep Plate 11"', 'Bravura Ø 29 cm - 31 cl. Ø 11 1/2” - 10 1/2 oz. 6', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 108, 'ea', 24.852, 'USD'),
  ('1312', '871557', 'Big Foot Door Wedge Rubber Grey', 'Door Stopper', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Wasserstrom', 'Sandolat', 'Banquet | Meeting Room and Miscelleanous', 'UTENSILIOS', 48, 'ea', 63.5811, 'USD'),
  ('1246', 'DW724MWSS', 'Carving Board', 'CARVING BOARD 24 IN L X 18 IN W WOOD W/ FRAME AND MODERN FEET STAINLESS STEEL', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Display', 'UTENSILIOS', 4, 'ea', 751.5919, 'USD'),
  ('1149', 'BCFRCS37M', 'Soup Cup without Handle', 'Fedra Cream Soup Bowl, 12.5 oz., with no handles, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 209, 'ea', 12.3, 'USD'),
  ('1331', '-', 'Couwboy Cauldron - Urban', 'https://cowboycauldron.com/products/the-urban-cowboy', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Couwboy Cauldron', 'Abastohotel', 'Banquet | Buffet Other', 'UTENSILIOS', 1, 'ea', NULL, 'USD'),
  ('1158', 'BCFRCP18', 'Coupe Plate, 7"', 'Fedra Coupe Plate, 7.08", bone china (24 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 9.276, 'USD'),
  ('1145', 'BCBVCB50', 'Cereal Bowl', 'Bravura Low Cereal Bowl Ø 15 cm - 50 cl Ø 6” - 16 5/6 oz 12', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 9.24, 'USD'),
  ('1200', '305 05 52 721', 'Honey Dispenser', 'Jambee jam/honey dispenser with wood base 23 oz', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 4, 'ea', 712.368, 'USD'),
  ('1271', '4583', 'Tray big', 'Pass arround cocktail -  95.5x28x1.8  base tray “Modul”
 melamine, black, surface matt, food-safe, dishwasher
safe, not suitable for microwave and combi steam oven', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 12, 'ea', 232.5, 'USD'),
  ('1144', 'BCPOPR28', 'Specialty Flat Coupe Plate 11"', 'Pose Flat Coupe Plate
28.8 x 27.1 cm
11 1/3” x 10 2/3”
12', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 144, 'ea', 16.416, 'USD'),
  ('1186', '2-1916-14B', 'Punch Bowl', 'Black Powder Coated Punch Bowl - Size 14" D', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'RCP', 'Steelite', 'Banquet', 'LOZA', 6, 'ea', 440.4324, 'USD'),
  ('1176', 'V3872', 'Beer Glass', 'Arcoroc, Stemmed Beer Cervoise 12.5 Oz (H:7.0'''' T:2.56'''' M:3.0'''' B:2.75''''), [''Soda Lime Glass''], (24 PC In A Case), Minimum Purchasing Unit CS', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet', 'CRISTALERIA', 396, 'ea', 5.57, 'USD'),
  ('1239', 'BU_BD3ONL', 'Bread Box - 3 Drawers', 'Oak 1.1 Bread Box: L: 349 x W: 530 x H: 190 mm (L: 13.7 × W: 20.9 × H: 7.4 in)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 4, 'ea', 641.13, 'USD'),
  ('1329', '-', 'Mobile Pizza Oven', 'Mobile Pizza Oven - Gozney Dome with Dome Stand and Dome Stand Cover. Peel and Turning Peel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Gozney', 'Gozney', 'Banquet | Buffet Other', 'UTENSILIOS', 1, 'sets', 2499.9875, 'USD'),
  ('1332', '-', 'Yakitori grill mill scale', 'https://millscale.co/products/yakitori-ii', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Mill Scale', 'Mill Scale', 'Banquet | Buffet Other', 'UTENSILIOS', 1, 'ea', 2493.75, 'USD'),
  ('1241', 'SET_GJO01', 'Mini Jar set Oak', 'Oak Mini Glass Jar set - Oak Mini Glass Jar set: L: 450 mm x W: 145 mm x H: 110 mm (L: 17.7 in x W: 5.7 in x H: 4.3 in)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'set', 310.205, 'USD'),
  ('1146', 'BCBVFBW10', 'Bowl 4"', 'Bravura Bowl, Ø 10 cm - 20 cl. Ø 4” - 6 3/4 oz (12 per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 7.68, 'USD'),
  ('1190', 'TBD', 'Damper 72', 'Damper for 72" round table', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 32, 'ea', 74.06, 'USD'),
  ('1169', '2900CT', 'Serving Tray', 'CAMTREAD® OVAL TRAYS Black 23 1/2" x 28 7/8" 60 x 73,5 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cambro', 'Equipo Hotel', 'Banquet', 'UTENSILIOS', 48, 'ea', 48.49, 'USD'),
  ('1211', '656039', 'Riser for Wooden Tray 1', 'Riser, 22-1/4"W x 14"D x 4"H, high for GN 1/1, matt black metal, oak frame', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 193.89, 'USD'),
  ('1278', '5405', 'Glass Miniature', 'Pass arround cocktail - glass miniature
 clear glass, for bridges “Modul” items 4584 and 4724
 item Ø / height in cm content in l PU
 5/8.6 0.1 6 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 87, 'ea', 22.8, 'USD'),
  ('1265', 'DWPELINPCCART6', 'PowerCell Storage Cart', 'PowerCell Storage Cart - L26" W18 1/8" H53 1/4" - Holds 6 units with coverups', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 3, 'ea', 736.2512, 'USD'),
  ('1308', 'Custom', 'Board Room Bloter', 'Meeting room blotter Black faux leather with embossed pattern L 55cm x W 41.3cm x H 1.3cm

DETAILS
Material:Faux leather
Color:Black 
With Logo', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Pantheon', 'Pantheon', 'Banquet | Meeting Room and Miscelleanous', 'UTENSILIOS', 48, 'ea', 45.92, 'USD'),
  ('1230', 'BW_307_D', 'Olive Wood Bowl 1', NULL, (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'ea', 273.35, 'USD'),
  ('1272', '4582', 'Tray medium', 'Pass arround cocktail -  72.5x28x1.8 base tray “Modul”
 melamine, black, surface matt, food-safe, dishwasher
safe, not suitable for microwave and combi steam oven', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 12, 'ea', 182, 'USD'),
  ('1143', 'BCPORBW44', 'Large asymmetric bowl 9"', 'Pose Large asymmetric bowl 24.4 x 20.9 cm - 44 cl 9 3/5” x 8 2/9” - 14 7/8 oz
12', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 108, 'ea', 16.974, 'USD'),
  ('1213', '656041', 'Riser for Wooden Tray 2', 'Riser, 14"W x 11-3/4"D x 4"H, high for GN 1/2, matt black metal, oak frame', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 173.295, 'USD'),
  ('1276', '1938', 'Party Spoon', 'Pass arround cocktail -  party spoon
 stainless steel 18/10, 4.3 mm thick, heavy quality, 21 
cm long
 polished', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'PLAQUE', 87, 'ea', 20.5, 'USD'),
  ('1212', '656029', 'Display Wooden Tray 2', 'Wooden Box, 12-3/4"W x 10-1/2"D x 2-3/4"H, GN 1/2, maple', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 24, 'ea', 84.63, 'USD'),
  ('1365', 'RA03', 'Cutting Board', 'Cutting Board, 24"W x 18"D x 2-1/4" thick, edge grain construction, Northern Hard Rock Maple, with Oil Finish, hand grips on each end, reversible', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'John Boos', 'John Boos', 'Banquet | BOH Bar', 'UTENSILIOS', 8, 'ea', 250, 'USD'),
  ('1147', 'BCBVRDP01', 'Raised Plate', 'Bravura 16 x 15 cm - Ht. 8.5 cm
6 2/9” x 5 6/7” - Ht. 3 1/4” 4', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 87, 'ea', 19.476, 'USD'),
  ('1274', '4584', 'Bridge', 'Pass arround cocktail -  bridge “Modul”
 melamine, black, surface matt, food-safe, dishwasher
safe, not suitable for microwave and combi steam oven, 
5 graded sockets (Ø top 5 cm, Ø bottom 2.5 cm), for 
several glass items (5257, 5405,...), with 4 rubber feet 
(black)
 l x w x h in cm
 PU
 41.5x7.7x6 
2 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 24, 'ea', 81.2, 'USD'),
  ('1175', '0026.112420', 'Red Wine 23oz', 'Zwiesel Glass Pure Bordeaux Glass, (130) 23 oz., dishwasher safe, lead free, sheer rim, crystal glass (0.41 each weight) (Per case = 6 each) (ecomm dealers 4 case increments; special box will be added cost)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet', 'CRISTALERIA', 188, 'ea', 8.87, 'USD'),
  ('1248', '656008', 'Chilling Station - Wooden Box', 'Chilling Station Wooden Box, 21-3/4"W x 13-3/4"D x 3-1/2"H, GN 1/1, maple', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Cold Display', 'UTENSILIOS', 8, 'ea', 229.835, 'USD'),
  ('1223', '652890', 'Bowls for Display Riser', '(CO1832) Salad/Serving Bowl, 123-1/2 oz., 12-3/4" dia. x 3-1/4"H, round, oven, microwave, freezer & dishwasher safe, porcelain, white cumulus, Caractere (US stocked item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 18, 'ea', 99.945, 'USD'),
  ('1224', '660606', 'Bowls for Display Riser', NULL, (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 18, 'ea', 99.945, 'USD'),
  ('1209', '650678', 'Wood Display Riser Set', 'Wood Display Riser Set of 3 - Ash Wood', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'set', 217.37, 'USD'),
  ('1148', 'BCBVJG35', 'Sauce Pourer', 'Bravura Jug
Ht. 16.5 cm - 36 cl
Ht. 6 1/2” - 12 2/7 oz
6', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'UTENSILIOS', 87, 'ea', 16.788, 'USD'),
  ('1386', '06.7585.6040', 'Marking Tray for Flatware', 'WMF S/S 11 x 8" Rectangle Serving Tray Stainless Steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'WMF', 'Latin Hotel', 'Banquet', 'UTENSILIOS', 36, 'ea', 46.7, 'USD'),
  ('1251', '656910', 'Chilling Box - Tray', '(1A+M125443) Tray, 20-3/4"W x 12-3/4"D x 1/2"H, rectangular, stackable, shockproof, thermal shock resistant (-148°F to + 176°F), food safe, non-porous, dishwasher safe, Nacryl® resin, anthracite, (US stock)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Cold Display', 'UTENSILIOS', 10, 'ea', 167.845, 'USD'),
  ('1150', 'BCFRSA18', 'Soup Cup Saucer', 'Fedra Saucer, 7.08", bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 209, 'ea', 6.864, 'USD'),
  ('1263', 'DWFB15136BK', 'Power cell cover up', 'PowerCell Cover Up SS Black', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 9, 'ea', 181.1306, 'USD'),
  ('1178', '3460012-6', 'High Ball Glass', 'Kyoto Longdrink 15 ½ oz - Set of six. - 463ml | 15 ½ oz
H 165 mm | 6 ½"
Ø 62 mm | 2 ½"', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Stolzle', 'Abastohotel', 'Banquet', 'CRISTALERIA', 267, 'ea', 5.148, 'USD'),
  ('1243', 'BU_OL001', 'Glass Jar Wooden Lid Oak', 'Large Oak Jar Lid: L: 207 mm x W: 207 mm x H: 29 mm (L: 8.15 in x W: 8.15 in x H: 1.4 in)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 128.9925, 'USD'),
  ('1189', 'TBD', 'Damper 66', 'Damper for 66" round table', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'GT Linens', 'GT Linens', 'Banquet  | Linen', 'BLANCOS', 22, 'ea', 68.42, 'USD'),
  ('1177', '3460015-6', 'OF Rock Glass', 'Kyoto Old Fashioned Tumbler 14 ½ oz - Set of six. - 433 ml | 14 ½ oz
H 94 mm | 3 ¾"
Ø 80 mm | 3"', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Stolzle', 'Abastohotel', 'Banquet', 'CRISTALERIA', 267, 'ea', 4.81, 'USD'),
  ('1339', 'RBB02', 'Silicone Bands', 'Band, 1/2"D, silicone, blue, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1340', 'RBP01', 'Silicone Bands', 'Band, 1/2"D, silicone, pink, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1341', 'RBY03', 'Silicone Bands', 'Band, 1/2"D, silicone, yellow, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1342', 'RBDG3', 'Silicone Bands', 'Band, 1/2"D, silicone, green, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1343', 'RBO05', 'Silicone Bands', 'Band, 1/2"D, silicone, orange, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1344', 'RBW06', 'Silicone Bands', 'Band, 1/2"D, silicone, white, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1345', 'RBR09', 'Silicone Bands', 'Band, 1/2"D, silicone, red, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1346', 'RBB06', 'Silicone Bands', 'Band, 1/2"D, silicone, black, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1347', 'RBBR7', 'Silicone Bands', 'Band, 1/2"D, silicone, brown, Arcoroc, Mix (fits OL166, OL167) (stock item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Proepta', 'Banquet | BOH Bar', 'UTENSILIOS', 0, 'pk', 364.5, 'USD'),
  ('1283', 'V871842003', 'Coffee and Tea Condiment Station', 'URBAN BUFFET TOWER H. cm 34', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Abert', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 8, 'ea', 178.89, 'USD'),
  ('1163', 'BCFRBR01', 'Ramekin', 'Fedra Butter Ramekin, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 267, 'ea', 4.596, 'USD'),
  ('1299', '122 05 02 710', 'Serving Spoons', 'Serving Spoon 34 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet | Holloware and Serving Pieces', 'PLAQUE', 51, 'ea', 24.036, 'USD'),
  ('1287', 'V870442CS5', 'Coffee and Tea Condiment Station', 'URBAN ORGANIZER CONTAINER L. cm 35, Larg. Cm 17.5, H. cm 4', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Abert', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 16, 'ea', 88.608, 'USD'),
  ('1247', 'PM-IB100', 'Sea Food Tray', 'Glass Ice Bin with metal frame and drainage tray', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Pantheon', 'Pantheon', 'Banquet | Buffet Display', 'UTENSILIOS', 2, 'ea', 708, 'USD'),
  ('1286', 'V870442CS4', 'Coffee and Tea Condiment Station', 'URBAN ORGANIZER CONTAINER L. cm 15, Larg. Cm 20, H. cm 8', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Abert', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 16, 'ea', 86.424, 'USD'),
  ('1227', '652885', 'Coupe Bowl Pepper', NULL, (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 18, 'ea', 75.745, 'USD'),
  ('1161', 'BCFRBW50', 'Bowl 17oz - Ø 5 1/5”', 'Fedra Bowl, 16.9 oz., bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 130, 'ea', 8.868, 'USD'),
  ('1303', '644293', 'Spoon Rest', '(RV1620) Cutlery Rest, 7-3/4" x 4" x 1-1/2"H, porcelain, matt slate, Revolution 2 (US stocked item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Holloware and Serving Pieces', 'UTENSILIOS', 51, 'ea', 22.455, 'USD'),
  ('1164', 'BCFRCR15', 'Creamer', 'Fedra Ceamer Ht. 8.5 cm - 21 cl Ht. 3 1/3” - 7 oz', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 116, 'ea', 9.588, 'USD'),
  ('1238', '652864', 'Platter Large', '(CO1746N-234) Serving Dish, 18-1/4" x 11-1/4" x 1-1/4"H oval, oven, microwave, freezer & dishwasher safe, porcelain, white cumulus, Caractere (US stocked item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 104.17, 'USD'),
  ('1244', 'BU_SP011', 'Wooden Oak Spoons', 'Oak Spoon: L: 230 mm x W: 40 mm x H: 38 mm (L: 9 in x W: 1.6 in x H: 1.5 in)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 24, 'ea', 52.0625, 'USD'),
  ('1134', '305 45 91 797', 'Steak Knife', 'Java steak knife 22,5 8,7/8 Ivory handle', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 89, 'ea', 11.856, 'USD'),
  ('1179', 'P3882', 'Martini Glass', 'Chef & Sommelier, Cabernet Cocktail 7.5 Oz (H:6.75'''' T:4.5'''' M:4.5'''' B:3.0''''), [''Krysta''], (12 PC In A Case), Minimum Purchasing Unit CS', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cardinal', 'Abastohotel', 'Banquet', 'CRISTALERIA', 130, 'ea', 8.06, 'USD'),
  ('1222', '660494', 'Marble Plate for Risers', 'White Marble Nacryl 20 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 24, 'ea', 50.625, 'USD'),
  ('1302', '305 05 81 539', 'Serving Tongs', '18 cm Pastry / bread tong', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet | Holloware and Serving Pieces', 'UTENSILIOS', 44, 'ea', 23.688, 'USD'),
  ('1292', '1717-96', 'Mini Table Top Trash Can Black', 'Midnight Bamboo Countertop Trash Bin - 5.00in L x 5.00in W x 7.00in H
12.7cm L x 12.7cm W x 17.78cm H', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cal-mil', 'Equipo Hotel', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 24, 'ea', 49.76, 'USD'),
  ('1122', '6323T502', 'Pepper Mill', 'Pepper Mill Stainless... 6" Salt & Pepper Mills from Trudeau', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'UTENSILIOS', 24, 'ea', 49.711, 'USD'),
  ('1217', '653040', 'Cake Stand 2 Cloche', 'Polycarbonate Cloche 31.2 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 96.485, 'USD'),
  ('1202', '650993', 'Sign  Holder', 'Lableclip holder bleech', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 108, 'ea', 9.12, 'USD'),
  ('1153', 'BCFRSC09', 'Stackable Expresso Cup', 'Fedra Expresso Cup, Ht. 2 1/6” - 3 3/8 oz., bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 130, 'ea', 7.488, 'USD'),
  ('1121', '6323T501', 'Salt Mill', 'Salt Shaker Stainless... 6" Salt & Pepper Mills from Trudeau', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet', 'UTENSILIOS', 24, 'ea', 42.8364, 'USD'),
  ('1228', '655563', 'Salad Bowl 1', NULL, (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 24, 'ea', 42.76, 'USD'),
  ('1229', '655564', 'Salad Bowl 2', NULL, (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 24, 'ea', 42.76, 'USD'),
  ('1236', '654820', 'Cocotte without Lid 8.75 oz', 'Cocotte without Lid 8.75 oz - Cinnamon 14 x 12 x 5 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 36, 'ea', 27.88, 'USD'),
  ('1237', '654822', 'Cocotte without Lid 8.75 oz', 'Cocotte without Lid 8.75 oz - Cardamom 14 x 12 x 5 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 36, 'ea', 27.88, 'USD'),
  ('1250', '656049', 'Chilling Box - Eutectic Plates', 'Eutectic Plate, 19"W x 11"D x 1"H, -12°C temperature, black', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Cold Display', 'UTENSILIOS', 16, 'ea', 62.7, 'USD'),
  ('1162', 'BCFRBW30', 'Bowl 10oz - Ø 4 3/8” -', 'Fedra Bowl, 10.14 oz., bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 130, 'ea', 6.432, 'USD'),
  ('1225', '655561', 'Bowls for Display Riser', '(CO2725N-254) Salad Bowl, 81-1/4 oz., 9-3/4" dia. x 3-1/4"H, round, oven, microwave, freezer & dishwasher safe, porcelain, cinnamon, Caractere (US stocked item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 18, 'ea', 52.615, 'USD'),
  ('1226', '655560', 'Bowls for Display Riser', '(CO2725N-255) Salad Bowl, 81-1/4 oz., 9-3/4" dia. x 3-1/4"H, round, oven, microwave, freezer & dishwasher safe, porcelain, cardamom, Caractere (US stocked item)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 18, 'ea', 52.615, 'USD'),
  ('1218', '654173', 'Cake Stand 1 Cloche', 'Polycarbonate Cloche 28 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 76.645, 'USD'),
  ('1315', 'H-8664', '5 Gallon Dual Sided Office Trash Can', 'simplehuman stainless steel Office Trash Can - 5 Gallon Recycling - Capacity 5 Gallon - Size L17xW9xH15"', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Uline', 'Sandolat', 'Banquet | Meeting Room and Miscelleanous', 'LIMPIEZA', 6, 'ea', 142.89, 'USD'),
  ('1205', '653076', 'Storage Jar', 'Glass Storage Jar 5 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 70.97, 'USD'),
  ('1141', 'BCBVCL16', 'Cover for Gourmet Deep Plates', 'Bravura Ø 16.5 cm - Ht. 9 cm. Ø 6 1/2” - Ht. 3 1/2”. 4', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 72, 'ea', 9.96, 'USD'),
  ('1215', '661543', 'Cake Stand 2', 'CARACTERE, CAKE STAND 33X14CM, Tumeric/Cardamom, 1, NOT STOCKED IN USA BUT CAN BE ORDERED AND AIFREIGHTED, Microwave oven and dishwasher safe, made in France', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'ea', 104.105, 'USD'),
  ('1165', 'BCFRSH01', 'Sugar Holder', 'Fedra Sugar Pack Holder, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 87, 'ea', 8.028, 'USD'),
  ('1130', '1170500022', 'Demitasse Spoon', 'La Tavola - Moka spoon Gualtiero Marchesi St. steel', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet', 'PLAQUE', 130, 'ea', 5.328, 'USD'),
  ('1293', '7401MM121', '1 Ltr Jug White', 'Thermos/Jug - Milk Server Vacuum Insulated
Stainless Liner w/ Wood Handle
L 6 5/8" W4 3/8" H 8 1/2" (1 L) White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 18, 'ea', 44.5932, 'USD'),
  ('1295', '7401MM123', '1 Ltr Jug Champagne', 'Thermos/Jug - Milk Server Vacuum Insulated
Stainless Liner w/ Wood Handle
L 6 5/8" W4 3/8" H 8 1/2" (1 L) Champagne', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 18, 'ea', 44.5932, 'USD'),
  ('1214', '661544', 'Cake Stand 1', 'CARACTERE, CAKE STAND 30X20CM, Nutmeg/Cinnamon, 1, NOT STOCKED IN USA BUT CAN BE ORDERED AND AIFREIGHTED, Microwave oven and dishwasher safe, made in France', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'ea', 98.615, 'USD'),
  ('1297', '122 05 01 442', 'Sauce Ladle', 'Sauce Ladle 15.6 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet | Holloware and Serving Pieces', 'UTENSILIOS', 36, 'ea', 18.696, 'USD'),
  ('1325', 'VC-CTB', 'Caster for 24x48', 'Metro Shelf Casters heavy duty', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Winco', 'Mepsa', 'Banquet | Carts and Transport', 'UTENSILIOS', 16, 'ea', 48.0136, 'USD'),
  ('1264', 'DWFB15133BK', 'Power cell cover up', 'PowerCell Cover Up SS Black', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'DW Haber', 'Steelite', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 9, 'ea', 84.4499, 'USD'),
  ('1337', '22440-3', 'Condiment Caddy', 'Heritage Jar Displays -112 I 12.75” W x 4.25” D x 4” H | 3 Jar', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Banquet | BOH Bar', 'UTENSILIOS', 8, 'ea', 93.27, 'USD'),
  ('1294', '7401MM120', '0.7 Ltr Jug White', 'Thermos/Jug - Milk Server Vacuum Insulated
Stainless Liner w/ Wood Handle
L 6 1/2" W 4 1/2" H 7 1/2" (0.7 L) White', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 18, 'ea', 40.6671, 'USD'),
  ('1296', '7401MM122', '0.7 Ltr Jug Champagne', 'Thermos/Jug - Milk Server Vacuum Insulated
Stainless Liner w/ Wood Handle
L 6 1/2" W 4 1/2" H 7 1/2" (0.7 L) Champagne', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Steelite', 'Steelite', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 18, 'ea', 40.6671, 'USD'),
  ('1199', 'H-1978O', 'Z Trolley', 'Z Rack for BQ Linen', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Uline', 'Sandolat', 'Banquet  | Linen', 'UTENSILIOS', 4, 'ea', 181.8, 'USD'),
  ('1154', 'BCFRSA13', 'Espresso Saucer', 'Fedra Saucer,Ø 13 cm / Ø 5 1/8”, bone china (12 each per case)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Rak', 'Proepta', 'Banquet', 'LOZA', 130, 'ea', 4.716, 'USD'),
  ('1216', '661548', 'Cake Stand 3', 'CARACTERE, CAKE STAND 26X10,5CM, Cardamom/Nutmeg, 1, NOT STOCKED IN USA BUT CAN BE ORDERED AND AIFREIGHTED, Microwave oven and dishwasher safe, made in France', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'ea', 89.52, 'USD'),
  ('1119', 'BCSPSS01', 'Salt Shaker', 'Spectra Salt Shaker', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'RAK', 'Proepta', 'Banquet', 'LOZA', 87, 'ea', 7.02, 'USD'),
  ('1120', 'BCSPPS01', 'Pepper Shaker', 'Spectra Pepper Shaker', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'RAK', 'Proepta', 'Banquet', 'LOZA', 87, 'ea', 7.02, 'USD'),
  ('1270', '656412', 'Lid Rest for Induction Cocottes', 'SS Lis Rest 13.5 x 9 x 7.5 cm', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Hot Display', 'UTENSILIOS', 18, 'ea', 39.37, 'USD'),
  ('1362', 'JP9730', 'Juicer, Lever / Crank Type', 'Cash & Carry Big Squeeze™ Juice Press, 11-1/2" x 7" x 17", manual, accommodates 5-3/4" glass, 3-pinion design, hand wash only, 18/8 stainless steel cone, cast iron construction, black coated finish, NSF (1 each minimum order)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', 'Banquet | BOH Bar', 'UTENSILIOS', 4, 'ea', 175.87, 'USD'),
  ('1322', 'VC-1836', 'Beverag Cage Shelf for 18x36', 'Beverage Cage Extra shelf', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Winco', 'Mepsa', 'Banquet | Carts and Transport', 'UTENSILIOS', 8, 'ea', 87.2575, 'USD'),
  ('1206', '653073', 'Storage Jar', 'Glass Storage Jar 2.5 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 58.05, 'USD'),
  ('1252', 'DV.501128', 'Glass Mini Flute', 'GLASS MINI FLUTE PILSNER SAMPLER D&V TASTERZ 3OZ', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet | Miniatures', 'CRISTALERIA', 144, 'ea', 3.81, 'USD'),
  ('1301', '903 05 81 004', 'Serving Tongs', '21 cm Hors d’oeuvre tongs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Broggi', 'Proepta', 'Banquet | Holloware and Serving Pieces', 'UTENSILIOS', 44, 'ea', 12.24, 'USD'),
  ('1232', '654543', 'Rectangle Oblong Dish', 'Rectangle Oblong Dish - White Cumulus - 34 x 25 x 6.5 - 2.8 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'ea', 77.12, 'USD'),
  ('1234', '654544', 'Rectangle Oblong Dish', 'Rectangle Oblong Dish - Cinnamon - 34 x 25 x 6.5 - 2.8 L', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'ea', 77.12, 'USD'),
  ('1253', 'DV.501180', 'Glass, D&V Tasterz 5oz.', 'GLASS, D&V TASTERZ MINI IPA 5OZ', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet | Miniatures', 'CRISTALERIA', 144, 'ea', 3.56, 'USD'),
  ('1273', '4585', 'Sppon Rest Bridge', 'Pass arround cocktail - spoon rest “Modul”
 melamine, black, surface matt, food-safe, dishwasher
safe, not suitable for microwave and combi steam oven, 
with 4 rubber feet (black)
 l x w x h in cm
 PU
 20x5x4 
2 pcs', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 24, 'ea', 24.9, 'USD'),
  ('1180', '26.112843', 'Shot Glasses', 'Pure Shot Glass (35)
3.2oz, 3.7x1.9”
(.09L, 9.4x4.8cm)
6/pack, GR49-S-115B*', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet', 'CRISTALERIA', 72, 'ea', 7.07, 'USD'),
  ('1181', '26.112841', 'Juice Glass', 'Pure Juice, Aperitif (15)
8.3oz, 5.5x2.4”
(.25L, 14x6.1cm)
6/pack, GR44-N-185H*', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Abastohotel', 'Banquet', 'CRISTALERIA', 72, 'ea', 7, 'USD'),
  ('1305', '55.0121.6140 and 55.0121.6043', 'Table Number Stand S/S', 'Pure Table number stand support', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'WMF', 'Latin Hotel', 'Banquet | Holloware and Serving Pieces', 'UTENSILIOS', 24, 'ea', 24.5, 'USD'),
  ('1207', '650494', 'Basket or Bread Presentation 1', 'WIRE BASKET, LARGE OVAL- Matt black metal  - 32,1 x 23,9 x 15,5 cm - 12 ¾ x 9 ½ x 6’’', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 8, 'ea', 71.715, 'USD'),
  ('1285', 'V870542V01', 'Coffee and Tea Condiment Station', 'URBAN ORGANIZER TRAY cm 20x19', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Abert', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 16, 'ea', 35.796, 'USD'),
  ('1221', '660297', 'Black Round Riser 3', 'Round Riser, large, metal, black, EN Scene (US stock)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 6, 'ea', 91.335, 'USD'),
  ('1257', 'ALU-00-012', 'China Spoon Appetizer Tasting 4"', 'Tasting Bowls 5.75”, 5oz (14.5cm, .15L)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Banquet | Miniatures', 'LOZA', 144, 'ea', 3.22, 'USD'),
  ('1377', 'SI6000', 'Ice Tote', 'Saf-T-Ice® Tote, 6 gallon, polycarbonate, rubber handle, with tri-grip feature, includes Saf-T-Ice® HACCP hanger for elevation to waist level, NSF', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'San Jamar', 'Sandolat', 'Banquet | BOH Bar', 'UTENSILIOS', 12, 'ea', 44.9372, 'USD'),
  ('1275', '4591', 'Cutlery Napkin Box', 'Pass arround cocktail -  cutlery/napkin box
 melamine, black, surface matt, food-safe, dishwasher
safe, with 4 rubber feet, not suitable for microwave and 
combi steam oven, for cocktail napkins folded to 1/8', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Zieher', 'Latin Hotel', 'Banquet | Cocktail Pass Around', 'UTENSILIOS', 24, 'ea', 21.7, 'USD'),
  ('1220', '660295', 'Black Round Riser 2', 'Round Riser, medium, metal, black, EN Scene (US stock)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 6, 'ea', 83.95, 'USD'),
  ('1369', '1851-5', 'Storage Jar / Ingredient Canister, Glass', 'Mixology Jar, 32 oz. capacity, 5-1/4" dia., x 4-1/2"H, double walled insulated base, stainless steel solid lid with silicone lining, glass, clear (cold pucks sold separately)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Cal-Mil', 'Equipo Hotel', 'Banquet | BOH Bar', 'UTENSILIOS', 12, 'ea', 41.19, 'USD'),
  ('1284', 'V870542CS2', 'Coffee and Tea Condiment Station', 'URBAN ORGANIZER CONTAINER L. cm 10, Larg. Cm 6.5, H. cm 4', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Abert', 'Proepta', 'Banquet | Coffee & Juice Display', 'UTENSILIOS', 16, 'ea', 30.24, 'USD'),
  ('1242', 'BU_GJ001', 'Glass Jar', 'Large Glass Jar: L: 218 mm x W: 218 mm x H: 165 mm (L: 8.6 in x W: 8.6 in x H: 6.5 in)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Craster', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 12, 'ea', 39.935, 'USD'),
  ('1219', '660293', 'Black Round Riser 1', 'Round Riser, small, metal, black, EN Scene (US stock)', (SELECT id FROM areas WHERE name = 'Banquet' LIMIT 1), 'Revol', 'Proepta', 'Banquet | Buffet Display', 'UTENSILIOS', 6, 'ea', 78.56, 'USD')
ON CONFLICT (code) DO NOTHING;
