-- ================================================
-- STEP 9: Items 2101–2127 of 2127
-- ================================================

INSERT INTO items (code, item_code, description, description_2, area_id, brand_current, supplier, category, item_type, qty_ordered, unit, price_unit, currency)
VALUES
  ('540', 'FP196', 'Arcoroc, Mix Hawthorne Strainer Copper (L:6.25'''' X W:3.375''''), [''18/10 Stainless Steel''], (1 PC In A Case), Minimum Purchasing Unit CS', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cardinal', 'Proepta', 'Bar Strainer', 'UTENSILIOS', 4, 'ea', 16.038, 'USD'),
  ('539', 'FP188', 'Arcoroc, Mix Shaker Copper 20.0 Oz (L:3.5'''' X W:2.44''''), [''18/10 Stainless Steel''], (1 PC In A Case), Minimum Purchasing Unit CS', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cardinal', 'Proepta', 'Cocktail Shaker 20oz', 'UTENSILIOS', 4, 'ea', 15.723, 'USD'),
  ('534', '12273/02', '10 cl - 3 ½ oz h 14.2 cm - 5 5⁄8” Max Ø 5.2 cm - 2”', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Luigi Bormioli', 'Proepta', 'Bitter / Dash Bottle', 'UTENSILIOS', 6, 'ea', 9.984, 'USD'),
  ('535', '12272/02', '10 cl - 3 ½ oz h 13.5 cm - 5 3 ⁄8” Max Ø 5.7 cm - 2 ¼”', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Luigi Bormioli', 'Proepta', 'Bitter / Dash Bottle', 'UTENSILIOS', 6, 'ea', 9.984, 'USD'),
  ('536', '301-02', 'Dust Cap, 1/2" L, for pour spouts (285-50 & 282-50), Made in USA (one gross per poly bag, one gross per carton = 144 each, minimum order one gross)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Spill-Stop', 'Spill-Stop', 'Drink Bar Mix Pourer Lid', 'UTENSILIOS', 2, 'ea', 28.8, 'USD'),
  ('558', 'M37023', 'Barfly Juicer, 8-7/8", with stainless steel pin, cast aluminum', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Mercer', 'Mepsa', 'Citrus Squeezer', 'UTENSILIOS', 2, 'ea', 24.1805, 'USD'),
  ('571', 'GR-3', 'Glass Rimmer / Margarita Salter with 3 Compartments', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Winco', 'Mepsa', 'Salt Rimmer', 'UTENSILIOS', 2, 'ea', 22.3077, 'USD'),
  ('565', 'AS-12', 'Scoop, 12 oz., aluminum (hand wash only) (Qty Break = 12 each)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Winco', 'Mepsa', 'Scoop', 'UTENSILIOS', 6, 'ea', 7.3993, 'USD'),
  ('542', 'FP193', 'Arcoroc, Mix Mesh Strainer Copper (L:8.75'''' X W:3.125''''), [''18/10 Stainless Steel''], (1 PC In A Case), Minimum Purchasing Unit CS', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cardinal', 'Proepta', 'Mesh Strainer', 'UTENSILIOS', 4, 'ea', 10.656, 'USD'),
  ('541', 'FP195', 'Arcoroc, Mix Julep Strainer Copper (L:7.0625'''' X W:3.0''''), [''18/10 Stainless Steel''], (1 PC In A Case), Minimum Purchasing Unit CS', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cardinal', 'Proepta', 'Julep Strainer', 'UTENSILIOS', 4, 'ea', 9.963, 'USD'),
  ('560', 'CAP07', 'Ellis Bar Knife, 9" overall, 4-1/2" blade, stainless steel blade, POM handle, Arcoroc, Mix', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cardinal', 'Proepta', 'Bar Knife', 'UTENSILIOS', 4, 'ea', 9.88, 'USD'),
  ('569', 'CHBST112', 'Champagne Bottle "Popper-Stopper", stainless steel', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', 'Bottle Stopper', 'UTENSILIOS', 4, 'ea', 9.22, 'USD'),
  ('544', 'CAP09', 'Muddler, 9-5/8", stainless steel, Arcoroc, Mix', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cardinal', 'Proepta', 'Muddler', 'UTENSILIOS', 4, 'ea', 9.07, 'USD'),
  ('545', 'CAP01', 'Tweezers, 6-1/4", stainless steel, Arcoroc, Mix', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cardinal', 'Proepta', 'Tongs, Tweezer', 'UTENSILIOS', 8, 'ea', 3.99, 'USD'),
  ('561', 'SS-821', 'Sharpening Stone, 8" x 2" x 1"H, rectangular, fine/medium grain, carbonized silicone (Qty Break = 12 each)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Winco', 'Mepsa', 'Sharpening Stone', 'UTENSILIOS', 2, 'ea', 14.9357, 'USD'),
  ('567', '7770-C', 'VacuVin® Vacuum Wine Preservation, includes: (1) 5" x 2-7/8" white pump, (1) 1-3/4" long gray stopper (carded)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Franmara', 'Franmara', 'Bottle Stopper', 'UTENSILIOS', 4, 'ea', 6.5, 'USD'),
  ('563', '100MCCW135', 'Camwear® Measuring Cup, 1 qt., molded handle, dishwasher safe, polycarbonate, clear, NSF', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Cambro', 'Equipo Hotel', 'Measuring Cup', 'UTENSILIOS', 2, 'ea', 9.53, 'USD'),
  ('521', '2.5.003.00.277', 'Ice/Sugar Tong 6” (15cm)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Fortessa', 'Hotel Depot', 'Ice Tongs', 'UTENSILIOS', 4, 'ea', 4.71, 'USD'),
  ('570', 'E5604', 'Cash & Carry FirmGrip® Zester/Lemon Peeler, 5-3/4" x 1-1/8" x 7/8", dishwasher safe, ergonomic soft grip handle, stainless steel, black (individually carded) (1 each minimum order)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', 'Lemon Lime Zester', 'UTENSILIOS', 4, 'ea', 4.4, 'USD'),
  ('546', 'M33071BKB', 'Y Peeler Black Handle', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Mercer', 'Mepsa', 'Vegetable Peeler, Manual', 'UTENSILIOS', 2, 'ea', 6.3079, 'USD'),
  ('568', '7771-C', 'VacuVin® Vacuum Wine Stopper, 1-3/4" long, ABS plastic, gray (2 each per pack) (carded)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Franmara', 'Franmara', 'Bottle Stopper', 'UTENSILIOS', 4, 'ea', 3, 'USD'),
  ('572', 'WCS871', 'Waiters Corkscrew - 4-1/2″ L x 7/8″ W x 7/8" - Stainless Steel', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'American Metalcraft', 'Equipo Hotel', 'Wine Key', 'UTENSILIOS', 4, 'ea', 2.85, 'USD'),
  ('550', '396', 'Pocket Bottle Opener, 7" flat, dishwasher safe, stainless steel (1 each minimum order)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'TableCraft Products', 'Equipo Hotel', 'Bottle Opener', 'UTENSILIOS', 6, 'ea', 1.63, 'USD'),
  ('553', 'PF-32', 'Funnel, 32 oz., 6-1/4" dia., round, plastic, white (Qty Break = 6 each)', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Winco', 'Mepsa', 'Funnel', 'UTENSILIOS', 2, 'ea', 3.3434, 'USD'),
  ('466', '-', 'Glass Honeycomb Display - Langstroth 19" for the Hospitality Industry', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Backyard Hive', 'Backyard Hive', 'Honeycomb Stand Presentation', 'UTENSILIOS', 1, 'ea', NULL, NULL),
  ('573', 'KB327 - 09', 'Booster Chair - Individual Seat Dimensions: 13” W x 9½” H x 12″ D (330 x 241 x 305 mm)- Brown', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Koala Care', 'Koala Care', 'Booster Seats', 'UTENSILIOS', 12, 'ea', NULL, NULL),
  ('574', '-', 'Trip Trap Natural Color', NULL, (SELECT id FROM areas WHERE name = 'Three Meal' LIMIT 1), 'Stokke', 'Stokke', 'High CHairs', 'UTENSILIOS', 12, 'ea', NULL, NULL)
ON CONFLICT (code) DO NOTHING;
